"""
UBP Music Study — Phase V: Deep Dive
=====================================================================
1. Analyze the TOP permutations from the random search — what musical
   structures do they embody?
2. Full 11-interval correlation (not just 1-6 semitones)
3. Alternative chord metric: average pairwise dH + "spread" (variance)
4. The Major 7th anomaly: XOR weight = 0 — investigate why
5. Nearest-codeword (snap) approach for chords instead of XOR
"""

import sys, math, random
from fractions import Fraction
from itertools import combinations, permutations

sys.path.insert(0, "/home/z/my-project")
from ubp_unified_v5 import GolayCodeEngine, LeechLatticeEngine

g = GolayCodeEngine()
l = LeechLatticeEngine(g)

def gray_code(n, bits=12):
    gc = n ^ (n >> 1)
    return [(gc >> (bits - 1 - i)) & 1 for i in range(bits)]

def vec_to_hex(v24):
    r = sum((1 << (7 - i)) for i in range(8) if v24[i])
    gg = sum((1 << (7 - i)) for i in range(8) if v24[8 + i])
    b = sum((1 << (7 - i)) for i in range(8) if v24[16 + i])
    return f"#{r:02x}{gg:02x}{b:02x}"

PITCH_NAMES = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"]
CONSONANCE_MAP = {
    0: "Unison", 1: "Min2", 2: "Maj2", 3: "Min3", 4: "Maj3",
    5: "P4", 6: "TT", 7: "P5", 8: "Min6", 9: "Maj6", 10: "Min7", 11: "Maj7"
}
# Standard consonance ranking (lower = more consonant)
CONSONANCE_RANK = {
    0: 1, 7: 2, 5: 3, 4: 3, 9: 3, 3: 4, 8: 4, 10: 4, 2: 5, 11: 5, 1: 6, 6: 6
}
COF_ORDER = [0, 7, 2, 9, 4, 11, 6, 1, 8, 3, 10, 5]


def pearson_r(x_vals, y_vals):
    n = len(x_vals)
    if n < 2: return 0.0
    mx, my = sum(x_vals)/n, sum(y_vals)/n
    cov = sum((x-mx)*(y-my) for x,y in zip(x_vals, y_vals))
    vx = sum((x-mx)**2 for x in x_vals)
    vy = sum((y-my)**2 for y in y_vals)
    if vx == 0 or vy == 0: return 0.0
    return cov / math.sqrt(vx * vy)


def encode_pitch_cw_map(perm):
    """Given a permutation [pitch_at_pos_0, pitch_at_pos_1, ...], return {pc: cw24}."""
    cw_map = {}
    for pitch_class in range(12):
        pos = perm.index(pitch_class)
        seed = gray_code(pos, 12)
        cw_map[pitch_class] = g.encode(seed)
    return cw_map


def interval_correlation(cw_map, full_range=False):
    """
    Compute Pearson r between consonance rank and Hamming distance.
    If full_range=True, uses intervals 1-11. Otherwise 1-6 (unordered).
    """
    by_interval = {}
    for pc_a, pc_b in combinations(range(12), 2):
        st_f = (pc_b - pc_a) % 12  # forward interval
        st_b = (pc_a - pc_b) % 12  # backward interval
        if full_range:
            # Use both directions to get all 11 intervals
            for st in [st_f, st_b]:
                if st == 0: continue
                hd = sum(x ^ y for x, y in zip(cw_map[pc_a], cw_map[pc_b]))
                by_interval.setdefault(st, []).append(hd)
        else:
            st = min(st_f, st_b)
            if st == 0: continue
            hd = sum(x ^ y for x, y in zip(cw_map[pc_a], cw_map[pc_b]))
            by_interval.setdefault(st, []).append(hd)

    x_vals, y_vals = [], []
    st_range = range(1, 12) if full_range else range(1, 7)
    for st in st_range:
        hds = by_interval.get(st, [])
        if not hds: continue
        x_vals.append(CONSONANCE_RANK[st])
        y_vals.append(sum(hds) / len(hds))
    return pearson_r(x_vals, y_vals)


# ═══════════════════════════════════════════════════════════════════════════════════
# V-A: FIND AND ANALYZE TOP PERMUTATIONS
# ═══════════════════════════════════════════════════════════════════════════════════

def analyze_permutation_musical_structure(perm):
    """Analyze what musical generator produces this permutation."""
    steps = [(perm[(i+1) % 12] - perm[i]) % 12 for i in range(12)]
    # Check if it's generated by a single interval
    for gen in range(1, 12):
        if math.gcd(gen, 12) == 1:  # generator must be coprime to 12
            test = [0]
            curr = 0
            for _ in range(11):
                curr = (curr + gen) % 12
                test.append(curr)
            if test == list(perm):
                return f"Generated by +{gen} semitones ({CONSONANCE_MAP[gen]})"
    return f"Steps: {steps}"


def run_va():
    print("=" * 80)
    print("PHASE V-A: TOP PERMUTATION ANALYSIS (50,000 samples)")
    print("=" * 80)

    random.seed(123)
    n_samples = 50000
    top_perms = []  # (r, perm)

    for _ in range(n_samples):
        perm = list(range(12))
        random.shuffle(perm)
        cw_map = encode_pitch_cw_map(perm)
        r = interval_correlation(cw_map)
        top_perms.append((r, perm))

    # Sort by absolute r
    top_perms.sort(key=lambda x: abs(x[0]), reverse=True)

    print(f"\n  TOP 20 PERMUTATIONS by |r|:")
    print(f"  {'#':>3s} | {'r':>8s} | {'R²':>7s} | Structure")
    print(f"  {'-'*3} | {'-'*8} | {'-'*7} | {'-'*40}")

    for i, (r, perm) in enumerate(top_perms[:20]):
        names = [PITCH_NAMES[p] for p in perm]
        struct = analyze_permutation_musical_structure(perm)
        print(f"  {i+1:>3d} | {r:>+8.4f} | {r**2:>7.4f} | {names} | {struct}")

    # Check: is Circle of Fifths in the top 20?
    cof_cw = encode_pitch_cw_map(COF_ORDER)
    cof_r = interval_correlation(cof_cw)
    cof_rank = None
    for i, (r, _) in enumerate(top_perms):
        if abs(r) <= abs(cof_r):
            cof_rank = i + 1
            break
    print(f"\n  Circle of Fifths (r={cof_r:+.4f}) would rank ~#{cof_rank} out of {n_samples}")

    # Tritone split
    tritone_perm = [0, 6, 1, 7, 2, 8, 3, 9, 4, 10, 5, 11]
    tri_cw = encode_pitch_cw_map(tritone_perm)
    tri_r = interval_correlation(tri_cw)
    tri_rank = None
    for i, (r, _) in enumerate(top_perms):
        if abs(r) <= abs(tri_r):
            tri_rank = i + 1
            break
    print(f"  Tritone Split  (r={tri_r:+.4f}) would rank ~#{tri_rank} out of {n_samples}")


# ═══════════════════════════════════════════════════════════════════════════════════
# V-B: FULL 11-INTERVAL CORRELATION
# ═══════════════════════════════════════════════════════════════════════════════════

def run_vb():
    print(f"\n{'=' * 80}")
    print("PHASE V-B: FULL 11-INTERVAL CORRELATION (ordered intervals)")
    print(f"{'=' * 80}")
    print("  (Using all 11 directed intervals per pitch pair, not just min(semitones, 12-semitones))")

    orderings = {
        "Chromatic": list(range(12)),
        "Circle of Fifths": COF_ORDER,
        "Tritone Split": [0, 6, 1, 7, 2, 8, 3, 9, 4, 10, 5, 11],
    }

    print(f"\n  {'Ordering':>25s} | {'r (1-6)':>8s} | {'r (1-11)':>9s} | {'Assessment (full)':>18s}")
    print(f"  {'-'*25} | {'-'*8} | {'-'*9} | {'-'*18}")

    for name, perm in orderings.items():
        cw_map = encode_pitch_cw_map(perm)
        r_half = interval_correlation(cw_map, full_range=False)
        r_full = interval_correlation(cw_map, full_range=True)
        strength = "STRONG" if abs(r_full) > 0.7 else "moderate" if abs(r_full) > 0.4 else "weak"
        print(f"  {name:>25s} | {r_half:>+8.4f} | {r_full:>+9.4f} | {strength:>18s}")

    # Detailed per-interval breakdown for CoF (full range)
    print(f"\n  DETAILED: Circle-of-Fifths Gray, all 11 intervals:")
    cw_map = encode_pitch_cw_map(COF_ORDER)
    by_interval = {}
    for pc_a, pc_b in combinations(range(12), 2):
        st_f = (pc_b - pc_a) % 12
        st_b = (pc_a - pc_b) % 12
        for st in [st_f, st_b]:
            if st == 0: continue
            hd = sum(x ^ y for x, y in zip(cw_map[pc_a], cw_map[pc_b]))
            by_interval.setdefault(st, []).append(hd)

    print(f"\n  {'Semi':>4s} | {'Interval':>6s} | {'CR':>3s} | {'Avg dH':>7s} | {'Min':>4s} | {'Max':>4s} | {'Var':>6s}")
    print(f"  {'-'*4} | {'-'*6} | {'-'*3} | {'-'*7} | {'-'*4} | {'-'*4} | {'-'*6}")
    for st in range(1, 12):
        hds = by_interval.get(st, [])
        if not hds: continue
        avg = sum(hds)/len(hds)
        var = sum((h-avg)**2 for h in hds)/len(hds)
        name = CONSONANCE_MAP[st]
        cr = CONSONANCE_RANK[st]
        print(f"  {st:>4d} | {name:>6s} | {cr:>3d} | {avg:>7.2f} | {min(hds):>4d} | {max(hds):>4d} | {var:>6.2f}")


# ═══════════════════════════════════════════════════════════════════════════════════
# V-C: ALTERNATIVE CHORD METRICS (pairwise distances, not XOR)
# ═══════════════════════════════════════════════════════════════════════════════════

def run_vc():
    print(f"\n{'=' * 80}")
    print("PHASE V-C: ALTERNATIVE CHORD METRICS — Pairwise Distance Analysis")
    print(f"{'=' * 80}")
    print("  XOR failed (everything maps to weight 8).")
    print("  New approach: characterize chord by pairwise Hamming distance distribution.")

    cw_map = encode_pitch_cw_map(COF_ORDER)

    chords = [
        ("C Maj",    [0,4,7],     "Consonant"),
        ("C Min",    [0,3,7],     "Consonant"),
        ("C Dim",    [0,3,6],     "Moderate"),
        ("C Aug",    [0,4,8],     "Moderate"),
        ("C Sus4",   [0,5,7],     "Consonant"),
        ("Cluster",  [0,1,2],     "Dissonant"),
        ("Cluster2", [0,1,6],     "Dissonant"),
        ("Maj7",     [0,4,7,11],  "Consonant"),
        ("Dom7",     [0,4,7,10],  "Consonant"),
        ("Dim7",     [0,3,6,9],   "Moderate"),
        ("WT 6",     [0,2,4,6,8,10], "Ambiguous"),
        ("Chrom 6",  list(range(6)), "Dissonant"),
        ("Diatonic", [0,2,4,5,7,9,11], "Consonant"),
        ("Pentatonic",[0,2,4,7,9], "Consonant"),
        ("Blues",    [0,3,5,6,7,10], "Mixed"),
    ]

    print(f"\n  {'Chord':>12s} | {'#notes':>6s} | {'Avg dH':>7s} | {'dH Var':>7s} | {'Min dH':>7s} | {'Max dH':>7s} | {'MaxInt':>6s} | {'Expect':>10s}")
    print(f"  {'-'*12} | {'-'*6} | {'-'*7} | {'-'*7} | {'-'*7} | {'-'*7} | {'-'*6} | {'-'*10}")

    results = []
    for name, pcs, expected in chords:
        distances = []
        max_interval = 0
        for a, b in combinations(pcs, 2):
            hd = sum(x ^ y for x, y in zip(cw_map[a], cw_map[b]))
            distances.append(hd)
            st = min((b-a)%12, (a-b)%12)
            max_interval = max(max_interval, st)
        avg = sum(distances)/len(distances) if distances else 0
        var = sum((d-avg)**2 for d in distances)/len(distances) if distances else 0
        print(f"  {name:>12s} | {len(pcs):>6d} | {avg:>7.2f} | {var:>7.2f} | {min(distances) if distances else 0:>7d} | {max(distances) if distances else 0:>7d} | {max_interval:>6d} | {expected:>10s}")
        results.append({"name": name, "expected": expected, "avg_dh": avg, "var_dh": var, "max_iv": max_interval, "n": len(pcs)})

    # The problem: we can't compare chords of different sizes directly.
    # But within same-size chords:
    print(f"\n  SAME-SIZE COMPARISONS:")
    for size in [3, 4, 6]:
        subset = [r for r in results if r["n"] == size]
        if len(subset) < 2:
            continue
        print(f"\n  {size}-note chords:")
        cons_map = {"Consonant": 1, "Moderate": 2, "Mixed": 3, "Ambiguous": 3, "Dissonant": 4}
        xs = [cons_map[r["expected"]] for r in subset]
        ys = [r["avg_dh"] for r in subset]
        r = pearson_r(xs, ys)
        print(f"    Consonance vs Avg dH: r = {r:+.4f}")
        for r_ in subset:
            print(f"      {r_['name']:>12s}: avg_dH={r_['avg_dh']:.2f}, var={r_['var_dh']:.2f} ({r_['expected']})")


# ═══════════════════════════════════════════════════════════════════════════════════
# V-D: MAJOR 7TH ANOMALY INVESTIGATION
# ═══════════════════════════════════════════════════════════════════════════════════

def run_vd():
    print(f"\n{'=' * 80}")
    print("PHASE V-D: MAJOR 7TH ANOMALY — Why does C-E-G-B XOR to weight 0?")
    print(f"{'=' * 80}")

    cw_map = encode_pitch_cw_map(COF_ORDER)

    # C=0, E=4, G=7, B=11
    maj7 = [0, 4, 7, 11]
    print(f"\n  CoF positions: {[COF_ORDER.index(p) for p in maj7]}")
    print(f"  CoF names:     {[PITCH_NAMES[p] for p in maj7]}")

    # The XOR of all 4 codewords
    result = list(cw_map[0])
    for pc in maj7[1:]:
        result = [a ^ b for a, b in zip(result, cw_map[pc])]
    print(f"  XOR result HW: {sum(result)}")
    print(f"  XOR result:    {result}")

    # This is weight 0 because in the linear code, C⊕E⊕G⊕B = 0
    # This means B is the XOR of C, E, and G — i.e., B "completes" the triad
    # to form a codeword-equivalent-to-zero structure.
    # Let's verify:
    xor_ceg = [a ^ b ^ c for a, b, c in zip(cw_map[0], cw_map[4], cw_map[7])]
    print(f"\n  C ⊕ E ⊕ G HW: {sum(xor_ceg)}")
    print(f"  B codeword HW: {sum(cw_map[11])}")
    print(f"  (C⊕E⊕G) == B?  {xor_ceg == cw_map[11]}")

    if xor_ceg == cw_map[11]:
        print(f"\n  ★ CONFIRMED: In CoF Gray encoding, B = C ⊕ E ⊕ G")
        print(f"  This means the Major 7th chord is a 'closed group' under XOR —")
        print(f"  it XORs to the identity (weight 0). In UBP terms, this chord")
        print(f"  collapses to the OnBit (NRCI=1.0), the most stable possible state.")
        print(f"  This is a genuine structural property of the CoF-Golay mapping.")

    # Check which other 4-note chords also XOR to 0
    print(f"\n  ALL 4-NOTE CHORDS THAT XOR TO WEIGHT 0:")
    count = 0
    for combo in combinations(range(12), 4):
        result = list(cw_map[combo[0]])
        for pc in combo[1:]:
            result = [a ^ b for a, b in zip(result, cw_map[pc])]
        if sum(result) == 0:
            count += 1
            names = [PITCH_NAMES[p] for p in combo]
            # Identify chord type
            intervals = sorted([min((b-a)%12, (a-b)%12) for a, b in combinations(combo, 2)])
            print(f"    {names} — intervals: {intervals}")
    print(f"  Total: {count} out of C(12,4) = 495")

    # Check which 3-note chords XOR to 0
    print(f"\n  ALL 3-NOTE CHORDS THAT XOR TO WEIGHT 0:")
    count3 = 0
    for combo in combinations(range(12), 3):
        result = list(cw_map[combo[0]])
        for pc in combo[1:]:
            result = [a ^ b for a, b in zip(result, cw_map[pc])]
        if sum(result) == 0:
            count3 += 1
            names = [PITCH_NAMES[p] for p in combo]
            intervals = sorted([min((b-a)%12, (a-b)%12) for a, b in combinations(combo, 2)])
            print(f"    {names} — intervals: {intervals}")
    print(f"  Total: {count3} out of C(12,3) = 220")


# ═══════════════════════════════════════════════════════════════════════════════════
# V-E: THE LEECH LATTICE DIMENSIONALITY — 2D PROJECTION FROM 24D
# ═══════════════════════════════════════════════════════════════════════════════════

def run_ve():
    print(f"\n{'=' * 80}")
    print("PHASE V-E: DIMENSIONALITY ANALYSIS — What information is in each 8-bit block?")
    print(f"{'=' * 80}")

    cw_map = encode_pitch_cw_map(COF_ORDER)

    print(f"\n  Each 24-bit codeword has 3 blocks of 8 bits (R, G, B in hex).")
    print(f"  Block 0 (bits 0-7)  = Red channel   = 'Noumenal core'")
    print(f"  Block 1 (bits 8-15) = Green channel = 'Phenomenal projection'")
    print(f"  Block 2 (bits 16-23)= Blue channel  = 'Leech shadow'")

    print(f"\n  {'Pitch':>5s} | {'CoF pos':>7s} | {'R (0-7)':>8s} | {'G (8-15)':>9s} | {'B (16-23)':>10s} | {'Total HW':>9s}")
    print(f"  {'-'*5} | {'-'*7} | {'-'*8} | {'-'*9} | {'-'*10} | {'-'*9}")

    for pc in range(12):
        cw = cw_map[pc]
        r_hw = sum(cw[0:8])
        g_hw = sum(cw[8:16])
        b_hw = sum(cw[16:24])
        pos = COF_ORDER.index(pc)
        print(f"  {PITCH_NAMES[pc]:>5s} | {pos:>7d} | {r_hw:>8d} | {g_hw:>9d} | {b_hw:>10d} | {r_hw+g_hw+b_hw:>9d}")

    # Average per block
    print(f"\n  Block weight statistics (11 non-zero pitches):")
    r_weights = [sum(cw_map[pc][0:8]) for pc in range(12) if pc != 0]
    g_weights = [sum(cw_map[pc][8:16]) for pc in range(12) if pc != 0]
    b_weights = [sum(cw_map[pc][16:24]) for pc in range(12) if pc != 0]
    print(f"    R block: avg={sum(r_weights)/len(r_weights):.2f}, range=[{min(r_weights)},{max(r_weights)}]")
    print(f"    G block: avg={sum(g_weights)/len(g_weights):.2f}, range=[{min(g_weights)},{max(g_weights)}]")
    print(f"    B block: avg={sum(b_weights)/len(b_weights):.2f}, range=[{min(b_weights)},{max(b_weights)}]")

    # Key question: how much of the Hamming distance is in each block?
    print(f"\n  HAMMING DISTANCE DECOMPOSITION BY BLOCK (CoF encoding):")
    print(f"  For each interval type, what fraction of dH is in each block?")

    by_interval_blocks = {}
    for pc_a, pc_b in combinations(range(12), 2):
        st = min((pc_b - pc_a) % 12, (pc_a - pc_b) % 12)
        if st == 0: continue
        r_hd = sum(cw_map[pc_a][i] ^ cw_map[pc_b][i] for i in range(8))
        g_hd = sum(cw_map[pc_a][i] ^ cw_map[pc_b][i] for i in range(8, 16))
        b_hd = sum(cw_map[pc_a][i] ^ cw_map[pc_b][i] for i in range(16, 24))
        by_interval_blocks.setdefault(st, []).append((r_hd, g_hd, b_hd))

    print(f"\n  {'Interval':>8s} | {'CR':>3s} | {'Avg R':>6s} | {'Avg G':>6s} | {'Avg B':>6s} | {'Total':>6s} | {'%R':>5s} | {'%G':>5s} | {'%B':>5s}")
    print(f"  {'-'*8} | {'-'*3} | {'-'*6} | {'-'*6} | {'-'*6} | {'-'*6} | {'-'*5} | {'-'*5} | {'-'*5}")

    for st in range(1, 7):
        blocks = by_interval_blocks.get(st, [])
        if not blocks: continue
        avg_r = sum(b[0] for b in blocks) / len(blocks)
        avg_g = sum(b[1] for b in blocks) / len(blocks)
        avg_b = sum(b[2] for b in blocks) / len(blocks)
        total = avg_r + avg_g + avg_b
        name = CONSONANCE_MAP[st]
        cr = CONSONANCE_RANK[st]
        pr = avg_r/total*100 if total > 0 else 0
        pg = avg_g/total*100 if total > 0 else 0
        pb = avg_b/total*100 if total > 0 else 0
        print(f"  {name:>8s} | {cr:>3d} | {avg_r:>6.2f} | {avg_g:>6.2f} | {avg_b:>6.2f} | {total:>6.2f} | {pr:>4.0f}% | {pg:>4.0f}% | {pb:>4.0f}%")


# ═══════════════════════════════════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    print("UBP MUSIC STUDY — Phase V: Deep Dive")
    print("System: ubp_unified_v5.py (live, no mocks)")
    print()

    run_va()
    run_vb()
    run_vc()
    run_vd()
    run_ve()

    print(f"\n{'=' * 80}")
    print("Phase V COMPLETE")
    print(f"{'=' * 80}")