"""
================================================================================
UBP GEOMETRIC REASONING V3.0 - SYSTEM-COMPATIBLE
================================================================================

CRITICAL FIXES from V1/V2:
1. USES REAL SYSTEM_KB VECTORS (lookup table, not regenerated)
2. HASH-BASED VECTORIZATION for new concepts (from ubp_integrated_engine_v1.py)
3. PROPER GOLAY ERROR CORRECTION (Encode∘Decode reflexive logic)
4. COMPATIBLE WITH ACTUAL UBP SYSTEM

Key Insight: System_KB vectors encode real properties (e.g., periodic table structure)
and were pre-computed, NOT generated by a simple formula. V3 respects this.

Author: E. R. A. Craig / Manus AI
Date: January 30, 2026
Version: 3.0 - System-Compatible Release
================================================================================
"""

import hashlib
import json
import os
from typing import Dict, List, Any, Optional, Tuple
from fractions import Fraction
from collections import defaultdict

# Import core UBP components
try:
    from ubp_core_v4_2_6_COMBINED import (
        GOLAY_DECODER,
        BinaryLinearAlgebra,
        UBPUltimateSubstrate,
        LeechPointScaled
    )
    from ubp_nrci_calculator import NRCI_CALCULATOR
    from hex_dictionary_v4_exact import HEX_DB_EXACT
    CORE_AVAILABLE = True
except ImportError:
    CORE_AVAILABLE = False
    print("[WARNING] Core UBP modules not available")


# ==============================================================================
# SECTION 1: CORRECT VECTOR GENERATION
# ==============================================================================

class UBPVectorEngine:
    """
    Handles vector generation using the CORRECT UBP protocol:
    1. For known concepts: Load from system_kb (lookup)
    2. For new concepts: Hash-based generation with Golay encoding
    """
    
    def __init__(self, system_kb_path: Optional[str] = None):
        """Initialize with optional system_kb path."""
        self.golay = GOLAY_DECODER
        self.system_kb = {}
        self.vector_cache = {}
        
        # Load system_kb if available
        if system_kb_path and os.path.exists(system_kb_path):
            self._load_system_kb(system_kb_path)
        
        # Try to load from hex_dictionary
        try:
            self.hex_db = HEX_DB_EXACT
            print(f"[VECTOR ENGINE] Loaded HexDB with {len(self.hex_db.registry)} entries")
        except:
            self.hex_db = None
            print("[VECTOR ENGINE] HexDB not available, using hash-based generation")
    
    def _load_system_kb(self, path: str):
        """Load system_kb and extract vectors."""
        try:
            with open(path, 'r') as f:
                data = json.load(f)
            
            for fingerprint, entry in data.items():
                name = entry.get('name', '')
                ubp_id = entry.get('ubp_id', '')
                vector = entry.get('vector', [])
                
                if vector and len(vector) == 24:
                    # Store by multiple keys for flexible lookup
                    self.system_kb[ubp_id] = vector
                    self.system_kb[name.lower()] = vector
                    self.system_kb[fingerprint] = vector
                    self.vector_cache[ubp_id] = vector
            
            print(f"[VECTOR ENGINE] Loaded {len(self.system_kb)} vectors from system_kb")
        except Exception as e:
            print(f"[VECTOR ENGINE] Could not load system_kb: {e}")
    
    def word_to_vector(self, word: str) -> List[int]:
        """
        Convert word to 24-bit vector using the CORRECT UBP protocol.
        
        Protocol (from ubp_integrated_engine_v1.py):
        1. SHA-256 hash the word
        2. Take first 3 bytes → mod 4096 (12-bit space)
        3. Expand to 24 bits
        4. Golay DECODE (error correct)
        5. Golay ENCODE (snap to valid codeword)
        
        This is the "Reflexive Logic": Repair(v) = Encode(Decode(v))
        """
        # Check if we have this in system_kb first
        word_lower = word.lower()
        if word_lower in self.system_kb:
            return self.system_kb[word_lower]
        
        # Check hex_db
        if self.hex_db:
            vec = self.hex_db.get_vector(word)
            if vec:
                return vec
        
        # Generate using hash-based method
        h = hashlib.sha256(word_lower.encode()).digest()
        val = int.from_bytes(h[:3], 'big') % 4096
        raw = [(val >> i) & 1 for i in range(23, -1, -1)]
        cw, _, _ = self.golay.decode(raw)
        return self.golay.encode(cw)
    
    def get_vector_by_id(self, ubp_id: str) -> Optional[List[int]]:
        """Get vector by UBP_ID from system_kb or hex_db."""
        if ubp_id in self.vector_cache:
            return self.vector_cache[ubp_id]
        
        if self.hex_db:
            return self.hex_db.get_vector(ubp_id)
        
        return None
    
    def hamming_distance(self, v1: List[int], v2: List[int]) -> int:
        """Calculate Hamming distance between two vectors."""
        return sum(a != b for a, b in zip(v1, v2))
    
    def snap_to_lattice(self, noisy_vector: List[int]) -> Tuple[List[int], int]:
        """
        Apply reflexive error correction: Repair(v) = Encode(Decode(v))
        Returns: (corrected_vector, errors_fixed)
        """
        if len(noisy_vector) != 24:
            raise ValueError(f"Vector must be 24 bits, got {len(noisy_vector)}")
        
        # Decode to find nearest valid codeword
        message, syndrome, errors = self.golay.decode(noisy_vector)
        
        # Re-encode to get the corrected vector
        corrected = self.golay.encode(message)
        
        # Count errors fixed
        errors_fixed = self.hamming_distance(noisy_vector, corrected)
        
        return corrected, errors_fixed


# ==============================================================================
# SECTION 2: MAIN REASONING ENGINE
# ==============================================================================

class UBPGeometricReasoningV3:
    """
    Complete UBP Geometric Reasoning Engine V3 - System Compatible.
    
    All 8 capabilities now use CORRECT vector handling.
    """
    
    def __init__(self, system_kb_path: Optional[str] = None):
        """Initialize the reasoning engine."""
        if not CORE_AVAILABLE:
            raise ImportError("Core UBP modules required")
        
        self.vector_engine = UBPVectorEngine(system_kb_path)
        self.golay = GOLAY_DECODER
        self.nrci_calc = NRCI_CALCULATOR
        self.leech = UBPUltimateSubstrate()
        
        print("[UBP V3] Geometric Reasoning Engine initialized")
        print(f"  - Vector Engine: Ready")
        print(f"  - Golay Decoder: Ready")
        print(f"  - NRCI Calculator: Ready")
        print(f"  - Leech Lattice: Λ₂₄ ready")
    
    # ==========================================================================
    # CAPABILITY 1: Vectorize Concept
    # ==========================================================================
    
    def vectorize_concept(self, concept: str) -> Dict[str, Any]:
        """
        Vectorize a concept using the CORRECT UBP protocol.
        
        Returns:
            dict with 'vector', 'fingerprint', 'domain', 'nrci', 'hamming_weight'
        """
        # Get vector using correct method
        vector = self.vector_engine.word_to_vector(concept)
        
        # Calculate fingerprint
        fingerprint = hashlib.sha256(concept.lower().encode()).hexdigest()
        
        # Decode to get message
        message, syndrome, errors = self.golay.decode(vector)
        
        # Extract domain from first 3 bits
        domain_bits = message[0:3]
        domain_val = sum(b << (2-i) for i, b in enumerate(domain_bits))
        domains = ["SUBSTANCE", "MECHANISM", "ORGANISM", "ALGORITHM",
                   "QUANTITY", "IMPERATIVE", "ENTROPY", "MEANING"]
        domain = domains[domain_val] if domain_val < len(domains) else "UNKNOWN"
        
        # Calculate NRCI
        nrci_result = self.nrci_calc.calculate_nrci(vector)
        nrci = nrci_result.global_nrci
        
        # Hamming weight
        hamming_weight = sum(vector)
        
        return {
            'concept': concept,
            'vector': vector,
            'fingerprint': fingerprint,
            'domain': domain,
            'nrci': float(nrci),
            'hamming_weight': hamming_weight,
            'errors_corrected': errors,
            'is_valid_codeword': syndrome
        }
    
    # ==========================================================================
    # CAPABILITY 2: Reason About
    # ==========================================================================
    
    def reason_about(self, query: str) -> Dict[str, Any]:
        """
        Execute full reasoning pipeline on a query.
        
        Pipeline:
        1. Vectorize query
        2. Check coherence
        3. Find resonance
        4. Return assessment
        """
        # Vectorize
        vec_result = self.vectorize_concept(query)
        vector = vec_result['vector']
        
        # Calculate coherence
        coherence = self.calculate_coherence(vector)
        
        # Find nearest concepts in system_kb
        resonance = self._find_resonance(vector)
        
        # Observer assessment
        status = "ACCEPTED" if coherence['nrci'] > 0.5 else "REJECTED"
        
        return {
            'status': status,
            'concept': query.upper(),
            'vector': vector,
            'vector_hex': ''.join(f"{b}" for b in vector),
            'resonance': resonance,
            'coherence': coherence,
            'domain': vec_result['domain']
        }
    
    def _find_resonance(self, vector: List[int]) -> Dict[str, Any]:
        """Find nearest concepts in system_kb."""
        if not self.vector_engine.system_kb:
            return {'status': 'NO_KB'}
        
        nearest = []
        for name, kb_vec in list(self.vector_engine.system_kb.items())[:100]:
            if isinstance(kb_vec, list) and len(kb_vec) == 24:
                dist = self.vector_engine.hamming_distance(vector, kb_vec)
                nearest.append({'name': name, 'distance': dist})
        
        nearest.sort(key=lambda x: x['distance'])
        
        if nearest:
            best = nearest[0]
            if best['distance'] == 0:
                return {'anchor': best['name'], 'distance': 0, 'type': 'PERFECT'}
            elif best['distance'] <= 3:
                return {'anchor': best['name'], 'distance': best['distance'], 'type': 'CLOSE'}
            else:
                return {'anchor': best['name'], 'distance': best['distance'], 'type': 'DISTANT'}
        
        return {'status': 'NO_MATCH'}
    
    # ==========================================================================
    # CAPABILITY 3: Find Counterpart
    # ==========================================================================
    
    def find_counterpart(self, concept: str, target_domain: str) -> Dict[str, Any]:
        """
        Find geometric equivalent in a different domain.
        """
        # Vectorize source
        source_vec = self.vector_engine.word_to_vector(concept)
        
        # Search system_kb for concepts in target domain
        candidates = []
        for name, vec in self.vector_engine.system_kb.items():
            if isinstance(vec, list) and len(vec) == 24:
                # Check domain
                msg, _, _ = self.golay.decode(vec)
                domain_bits = msg[0:3]
                domain_val = sum(b << (2-i) for i, b in enumerate(domain_bits))
                domains = ["SUBSTANCE", "MECHANISM", "ORGANISM", "ALGORITHM",
                           "QUANTITY", "IMPERATIVE", "ENTROPY", "MEANING"]
                domain = domains[domain_val] if domain_val < len(domains) else "UNKNOWN"
                
                if domain.upper() == target_domain.upper():
                    dist = self.vector_engine.hamming_distance(source_vec, vec)
                    candidates.append({'name': name, 'distance': dist, 'vector': vec})
        
        if candidates:
            candidates.sort(key=lambda x: x['distance'])
            best = candidates[0]
            return {
                'source_concept': concept,
                'target_domain': target_domain,
                'counterpart': best['name'],
                'hamming_distance': best['distance'],
                'status': 'FOUND'
            }
        
        return {
            'source_concept': concept,
            'target_domain': target_domain,
            'status': 'NOT_FOUND'
        }
    
    # ==========================================================================
    # CAPABILITY 4: Calculate Coherence
    # ==========================================================================
    
    def calculate_coherence(self, vector: List[int]) -> Dict[str, Any]:
        """
        Calculate NRCI and tetradic health.
        """
        nrci_result = self.nrci_calc.calculate_nrci(vector)
        
        return {
            'nrci': float(nrci_result.global_nrci),
            'health': {
                'reality': float(nrci_result.reality_health),
                'info': float(nrci_result.info_health),
                'activation': float(nrci_result.activation_health),
                'potential': float(nrci_result.potential_health)
            },
            'regime': nrci_result.coherence_regime,
            'stability': float(nrci_result.stability_score),
            'symmetry_tax': float(nrci_result.symmetry_tax)
        }
    
    # ==========================================================================
    # CAPABILITY 5: Snap to Lattice
    # ==========================================================================
    
    def snap_to_lattice(self, noisy_vector: List[int]) -> Dict[str, Any]:
        """
        Apply Golay error correction.
        """
        corrected, errors_fixed = self.vector_engine.snap_to_lattice(noisy_vector)
        
        # Find nearest anchor
        resonance = self._find_resonance(corrected)
        
        status = "PERFECT" if errors_fixed == 0 else "CORRECTED" if errors_fixed <= 3 else "DEEP_HOLE"
        
        return {
            'original_vector': noisy_vector,
            'corrected_vector': corrected,
            'errors_fixed': errors_fixed,
            'status': status,
            'nearest_anchor': resonance.get('anchor', 'NONE')
        }
    
    # ==========================================================================
    # CAPABILITY 6: Query Memory
    # ==========================================================================
    
    def query_memory(self, search_term: str, max_results: int = 12) -> List[Dict[str, Any]]:
        """
        Query system_kb by Hamming distance.
        """
        search_vec = self.vector_engine.word_to_vector(search_term)
        
        results = []
        for name, vec in self.vector_engine.system_kb.items():
            if isinstance(vec, list) and len(vec) == 24:
                dist = self.vector_engine.hamming_distance(search_vec, vec)
                results.append({
                    'name': name,
                    'hamming_distance': dist,
                    'vector': vec
                })
        
        results.sort(key=lambda x: x['hamming_distance'])
        return results[:max_results]
    
    # ==========================================================================
    # CAPABILITY 7: Validate Concept
    # ==========================================================================
    
    def validate_concept(self, concept_data: dict) -> Dict[str, Any]:
        """
        Run concept through 5-phase research protocol.
        """
        # Phase 1: Initiation
        required_fields = ['name', 'math', 'language', 'script', 'tags']
        phase1 = 'PASS' if all(f in concept_data for f in required_fields) else 'FAIL'
        
        if phase1 == 'FAIL':
            return {
                'phase_1_initiation': 'FAIL',
                'phase_2_development': 'SKIPPED',
                'phase_3_distillation': 'SKIPPED',
                'phase_4_promotion': 'SKIPPED',
                'phase_5_archival': 'SKIPPED',
                'promotion_eligible': False
            }
        
        # Phase 2: Development (vectorize)
        vec_result = self.vectorize_concept(concept_data['name'])
        phase2 = 'PASS'
        
        # Phase 3: Distillation (coherence check)
        coherence = self.calculate_coherence(vec_result['vector'])
        phase3 = f"PASS (Coherent)" if coherence['nrci'] > 0.5 else "FAIL (Incoherent)"
        
        # Phase 4: Promotion
        phase4 = 'PASS' if coherence['nrci'] > 0.5 else 'FAIL'
        
        # Phase 5: Archival
        phase5 = 'READY' if phase4 == 'PASS' else 'NOT_READY'
        
        return {
            'phase_1_initiation': phase1,
            'phase_2_development': phase2,
            'phase_3_distillation': phase3,
            'phase_4_promotion': phase4,
            'phase_5_archival': phase5,
            'promotion_eligible': phase4 == 'PASS',
            'nrci': coherence['nrci'],
            'vector': vec_result['vector']
        }
    
    # ==========================================================================
    # CAPABILITY 8: Archive to KB
    # ==========================================================================
    
    def archive_to_kb(self, concept_data: dict) -> str:
        """
        Format concept for KB archival.
        """
        # Generate vector
        name = concept_data.get('name', 'UNKNOWN')
        vec_result = self.vectorize_concept(name)
        
        # Create KB entry
        entry = {
            vec_result['fingerprint']: {
                'ubp_id': concept_data.get('ubp_id', f"CUSTOM_{name.upper()}"),
                'name': name,
                'math': concept_data.get('math', ''),
                'language': concept_data.get('language', ''),
                'script': concept_data.get('script', ''),
                'tags': concept_data.get('tags', []),
                'nrci': str(Fraction(vec_result['nrci']).limit_denominator()),
                'fingerprint': vec_result['fingerprint'],
                'vector': vec_result['vector']
            }
        }
        
        return json.dumps(entry, indent=2)


# ==============================================================================
# CONVENIENCE FUNCTIONS
# ==============================================================================

def get_reasoning_engine(system_kb_path: Optional[str] = None) -> UBPGeometricReasoningV3:
    """Get a configured reasoning engine instance."""
    return UBPGeometricReasoningV3(system_kb_path)


# ==============================================================================
# MAIN - DEMONSTRATION
# ==============================================================================

if __name__ == "__main__":
    print("\n" + "="*80)
    print("UBP GEOMETRIC REASONING V3 - SYSTEM-COMPATIBLE")
    print("="*80)
    
    # Initialize
    ubp = get_reasoning_engine()
    
    # Test 1: Vectorize
    print("\n[TEST 1] Vectorize Concept:")
    result = ubp.vectorize_concept("Energy")
    print(f"  Concept: {result['concept']}")
    print(f"  Domain: {result['domain']}")
    print(f"  NRCI: {result['nrci']:.4f}")
    print(f"  Vector: {result['vector'][:12]}... (truncated)")
    
    # Test 2: Coherence
    print("\n[TEST 2] Calculate Coherence:")
    test_vec = [1, 0, 1, 0] * 6
    coherence = ubp.calculate_coherence(test_vec)
    print(f"  NRCI: {coherence['nrci']:.4f}")
    print(f"  Regime: {coherence['regime']}")
    
    # Test 3: Error Correction
    print("\n[TEST 3] Snap to Lattice:")
    noisy = [1, 0, 0, 0] * 6
    result = ubp.snap_to_lattice(noisy)
    print(f"  Errors Fixed: {result['errors_fixed']}")
    print(f"  Status: {result['status']}")
    
    print("\n" + "="*80)
    print("✓ V3 READY - SYSTEM COMPATIBLE")
    print("="*80)
