#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
================================================================================
  GLM-3 GRIESS  —  the even part of the Monster's algebra, built and used
================================================================================

  Part of:  The Geometric Language Machine, third generation (GLM-3).
  Layer  :  Tier 2 — the algebra the reasoner actually computes in.
  Deps   :  glm3_leech2.py, ../glm2/glm2_lattice.py.  Exact rationals only.

  ------------------------------------------------------------------------
  What is built here
  ------------------------------------------------------------------------

  Let z be a 2B involution of the Monster M.  Its centraliser is
  N = 2^(1+24).Co_1, and z acts on the 196,884-dimensional Griess algebra
  V with eigenvalues +1 and -1:

        V  =  V^+  (+)  V^-,        V^+ = A (+) B,      V^- = C
        196,884   =   300 + 98,280    +    98,304 .

  Because z is an algebra automorphism, V^+ is a SUBALGEBRA — the even part.
  This module constructs it exactly:

      A  = Sym^2(R^24)      symmetric 24x24 rational matrices        300
      B  = span{ b_lam }    one basis vector per type-2 class of
                            Lambda/2Lambda                        98,280
                                                                  -------
                                                                  98,580

  with the commutative product (lam, mu are minimal vectors in the standard
  normalisation |lam|^2 = 4; P_lam = lam lam^T):

      A1 . A2   =  (A1 A2 + A2 A1) / 2                       (Jordan)
      A  . b_lam=  (1/4) (lam^T A lam) b_lam
      b_lam . b_lam = (1/4) P_lam
      b_lam . b_mu  = (1/4) b_{lam+mu}    if lam.mu = +-2, so that the
                                          class lam+mu is again type 2
                    =  0                  if lam.mu = 0 or +-1,

  and the invariant bilinear form

      (A1, A2) = 2 tr(A1 A2),   (b_lam, b_mu) = 2 [lam = mu],   (A, b) = 0.

  ------------------------------------------------------------------------
  Nothing here is quoted from a table
  ------------------------------------------------------------------------

  The five constants (1/2, 1/4, 1/4, 1/4, and the 2 in the form) are not
  taken from the literature.  They are FORCED, and the derivation is short
  enough to state:

    1.  Equivariance under N.  The 2^24 = Lambda/2Lambda inside N acts on
        b_lam by the sign (-1)^B(lam,mu) and trivially on A, and Co_0 acts
        naturally on both.  An N-equivariant commutative product must have
        exactly the shape written above, with unknown scalars
        alpha, beta, gamma, delta.
    2.  An identity element.  It must be N-invariant, so it lies in A and is
        a multiple of the identity matrix; e = 1 forces 2 alpha = 1 and
        4 beta = 1, i.e. alpha = 1/2, beta = 1/4.
    3.  Frobenius.  Requiring (x.y, w) = (x, y.w) kills the possible
        (trace) I term in b.b and ties the form to gamma.
    4.  The fusion law.  Asking that
            a_lam = (1/8) P_lam + (1/2) b_lam
        be an idempotent whose adjoint has spectrum {1, 0, 1/4, 1/32} —
        the Monster's Ising fusion law — forces gamma r^2 = 1/16 and
        r delta = 1/8, i.e. gamma = delta = 1/4 in the normalisation
        (a_lam, a_lam) = 1.

  Everything after that is computed and checked by execution:

    * a_lam is an idempotent with (a_lam, a_lam) = 1  (Majorana normalised);
    * ad(a_lam) has spectrum exactly {1, 0, 1/4, 1/32} with eigenspace
      dimensions 1, 49,152, 2,323, 47,104 summing to 98,580;
    * all nine Monster fusion rules hold, including the graded ones
      V_{1/4} V_{1/4} < V_1 + V_0 and V_{1/32} V_{1/32} < V_1 + V_0 + V_{1/4};
    * the Miyamoto involution of a_lam is exactly the extraspecial sign
      automorphism x_lam, so it is an automorphism because the group acts;
    * two axes generate a subalgebra of dimension 3, 5 or 2 with inner
      product 1/8, 1/32 or 0 according to whether lam.mu is +-2, +-1 or 0 —
      that is, the Norton-Sakuma algebras 2A, 4A and 2B, obtained by
      computing a closure rather than by copying structure constants.

  ------------------------------------------------------------------------
  What is NOT built
  ------------------------------------------------------------------------

  The odd part C = 24 (x) 4096 is not built, so neither is the full 196,884.
  Two consequences are stated honestly and re-checked in the audit:
  restricted to the even part the two axes (1/8)P_lam +- (1/2)b_lam have the
  SAME Miyamoto involution (the C-part separates them), and the group
  generated by Miyamoto involutions is the elementary abelian 2^24 rather
  than the dihedral groups one sees in the whole Monster.  The Norton-Sakuma
  types are therefore identified by dimension and inner product, which is
  already enough to separate 2A, 4A and 2B.

      python3 glm3_griess.py            # algebra self-audit
      python3 glm3_griess.py --quick    # skip the slow sweeps
================================================================================
"""

from __future__ import annotations

import sys
from fractions import Fraction as F
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

from glm3_common import banner, fmt_int
import glm3_leech2 as L2

import glm2_lattice as LAT

__all__ = [
    "DIM_A", "DIM_B", "DIM_EVEN", "ALPHA", "BETA", "GAMMA", "DELTA",
    "type2_table", "class_representative", "std_inner",
    "GriessVector", "zero", "identity", "b_vector", "a_matrix", "outer",
    "axis", "axis_of_class", "spectrum_dimensions",
    "eigen_filter", "in_eigenspace", "fusion_report", "miyamoto_signs",
    "apply_sign_automorphism", "is_automorphism_on",
    "subalgebra_closure", "norton_sakuma_report", "griess_audit",
]

DIM_A = 300
DIM_B = 98280
DIM_EVEN = DIM_A + DIM_B
N = 24

ALPHA = F(1, 2)     # A . A   = alpha (A1 A2 + A2 A1)
BETA = F(1, 4)      # A . b   = beta (lam^T A lam) b
GAMMA = F(1, 4)     # b . b   = gamma P_lam
DELTA = F(1, 4)     # b_lam . b_mu = delta b_{lam+mu}
FORM_A = F(2)       # (A1, A2) = FORM_A tr(A1 A2)
FORM_B = F(2)       # (b, b)   = FORM_B

Matrix = List[List[F]]

_TABLE: Optional[Dict[int, Tuple[int, ...]]] = None


# ══════════════════════════════════════════════════════════════════════════════
# §1.  THE INDEX SET:  98,280 TYPE-2 CLASSES
# ══════════════════════════════════════════════════════════════════════════════

def type2_table() -> Dict[int, Tuple[int, ...]]:
    """
    class -> a chosen minimal vector in it.  Built once by streaming the
    196,560 minimal vectors of Lambda; the choice of +-v does not matter,
    because every formula below uses either P_lam (even in the sign) or the
    class sum, which is sign-blind.
    """
    global _TABLE
    if _TABLE is None:
        _TABLE = L2.type2_class_table()
    return _TABLE


def class_representative(cls: int) -> Tuple[int, ...]:
    return type2_table()[cls]


def std_inner(v: Sequence[int], w: Sequence[int]) -> F:
    """
    The inner product in the STANDARD normalisation, in which minimal
    vectors have norm 4.  GLM-2 stores Lambda in the "times sqrt 8" integer
    model, so this is the integer inner product divided by 8.
    """
    return F(LAT.inner(v, w), 8)


# ══════════════════════════════════════════════════════════════════════════════
# §2.  VECTORS OF THE EVEN ALGEBRA
# ══════════════════════════════════════════════════════════════════════════════

def _zero_matrix() -> Matrix:
    return [[F(0)] * N for _ in range(N)]


def outer(v: Sequence[int]) -> Matrix:
    """P_lam = lam lam^T for the standard normalisation lam = v / sqrt 8."""
    return [[F(int(v[i]) * int(v[j]), 8) for j in range(N)] for i in range(N)]


class GriessVector:
    """
    An element of the even part: a symmetric 24x24 rational matrix (the
    A-part) together with a finitely supported map from type-2 classes to Q
    (the B-part).  Sparse in B, dense in A — which is the right trade-off,
    since A is 300-dimensional and B is 98,280-dimensional.
    """

    __slots__ = ("A", "B")

    def __init__(self, A: Optional[Matrix] = None,
                 B: Optional[Dict[int, F]] = None) -> None:
        self.A: Matrix = A if A is not None else _zero_matrix()
        self.B: Dict[int, F] = {k: F(v) for k, v in (B or {}).items() if v != 0}

    # ── linear structure ────────────────────────────────────────────────
    def __add__(self, other: "GriessVector") -> "GriessVector":
        A = [[self.A[i][j] + other.A[i][j] for j in range(N)] for i in range(N)]
        B = dict(self.B)
        for k, v in other.B.items():
            s = B.get(k, F(0)) + v
            if s:
                B[k] = s
            else:
                B.pop(k, None)
        return GriessVector(A, B)

    def scale(self, c) -> "GriessVector":
        c = F(c)
        A = [[c * self.A[i][j] for j in range(N)] for i in range(N)]
        return GriessVector(A, {k: c * v for k, v in self.B.items()} if c else {})

    def __sub__(self, other: "GriessVector") -> "GriessVector":
        return self + other.scale(-1)

    def is_zero(self) -> bool:
        return (not self.B) and all(x == 0 for row in self.A for x in row)

    def __eq__(self, other: object) -> bool:
        return isinstance(other, GriessVector) and (self - other).is_zero()

    def __repr__(self) -> str:
        tr = sum(self.A[i][i] for i in range(N))
        return (f"GriessVector(A: trace {tr}, "
                f"B: {len(self.B)} classes, norm {self.form(self)})")

    # ── algebra ─────────────────────────────────────────────────────────
    def mul(self, other: "GriessVector") -> "GriessVector":
        """The Griess product, restricted to the even part."""
        tab = type2_table()
        A = _mat_scale(ALPHA, _mat_add(_mat_mul(self.A, other.A),
                                       _mat_mul(other.A, self.A)))
        B: Dict[int, F] = {}

        def bump(c: int, coef: F) -> None:
            if coef:
                s = B.get(c, F(0)) + coef
                if s:
                    B[c] = s
                else:
                    B.pop(c, None)

        for c, coef in other.B.items():
            bump(c, BETA * _quad(self.A, tab[c]) * coef)
        for c, coef in self.B.items():
            bump(c, BETA * _quad(other.A, tab[c]) * coef)
        for c1, k1 in self.B.items():
            for c2, k2 in other.B.items():
                if c1 == c2:
                    A = _mat_add(A, _mat_scale(GAMMA * k1 * k2,
                                               outer(tab[c1])))
                else:
                    c3 = c1 ^ c2
                    if c3 in tab:
                        bump(c3, DELTA * k1 * k2)
        return GriessVector(A, B)

    def form(self, other: "GriessVector") -> F:
        """The invariant bilinear form."""
        s = sum(self.A[i][j] * other.A[i][j] for i in range(N) for j in range(N))
        t = sum(k * other.B.get(c, F(0)) for c, k in self.B.items())
        return FORM_A * s + FORM_B * t

    def support(self) -> int:
        return len(self.B)


def _mat_add(X: Matrix, Y: Matrix) -> Matrix:
    return [[X[i][j] + Y[i][j] for j in range(N)] for i in range(N)]


def _mat_scale(c: F, X: Matrix) -> Matrix:
    return [[c * X[i][j] for j in range(N)] for i in range(N)]


def _mat_mul(X: Matrix, Y: Matrix) -> Matrix:
    out = _zero_matrix()
    for i in range(N):
        Xi = X[i]
        oi = out[i]
        for k in range(N):
            x = Xi[k]
            if x:
                Yk = Y[k]
                for j in range(N):
                    if Yk[j]:
                        oi[j] += x * Yk[j]
    return out


def _quad(X: Matrix, v: Sequence[int]) -> F:
    """lam^T X lam for lam = v / sqrt 8."""
    total = F(0)
    idx = [i for i in range(N) if v[i]]
    for i in idx:
        Xi = X[i]
        vi = int(v[i])
        for j in idx:
            if Xi[j]:
                total += F(vi * int(v[j]), 8) * Xi[j]
    return total


# ── constructors ────────────────────────────────────────────────────────────

def zero() -> GriessVector:
    return GriessVector()


def identity() -> GriessVector:
    """The identity element of the even algebra: the identity matrix in A."""
    A = _zero_matrix()
    for i in range(N):
        A[i][i] = F(1)
    return GriessVector(A)


def b_vector(cls: int, coefficient=1) -> GriessVector:
    return GriessVector(None, {cls: F(coefficient)})


def a_matrix(X: Matrix) -> GriessVector:
    return GriessVector([[F(x) for x in row] for row in X])


def axis(cls: int, sign: int = 1) -> GriessVector:
    """
    The Majorana axis of a type-2 class:

        a_lam^eps  =  (1/8) P_lam  +  eps (1/2) b_lam,     eps = +-1.

    Both signs are idempotents with (a, a) = 1 and the Monster spectrum; the
    two are exchanged by the extraspecial group, and the even part cannot
    tell them apart by their Miyamoto involutions (see the module header).
    """
    if sign not in (1, -1):
        raise ValueError("axis: sign must be +1 or -1")
    v = class_representative(cls)
    return GriessVector(_mat_scale(F(1, 8), outer(v)),
                        {cls: F(sign, 2)})


def axis_of_class(cls: int) -> GriessVector:
    return axis(cls, 1)


# ══════════════════════════════════════════════════════════════════════════════
# §3.  THE SPECTRUM OF AN AXIS
# ══════════════════════════════════════════════════════════════════════════════

EIGENVALUES = (F(1), F(0), F(1, 4), F(1, 32))


def spectrum_dimensions() -> Dict[str, int]:
    """
    The exact dimensions of the four eigenspaces of ad(a_lam) on the whole
    98,580-dimensional even algebra, counted rather than sampled.

      * A splits as  <a-part>  +  {lam w^T + w lam^T : w perp lam}  (23)
        + traceless Sym^2(lam-perp) (275) + the 3-space <P, I, b_lam>;
      * b_mu with lam.mu = 0 (46,575 classes)   -> eigenvalue 0
        b_mu with |lam.mu| = 1 (47,104 classes) -> eigenvalue 1/32
        the 4,600 classes with |lam.mu| = 2 pair up into 2,300 blocks
        {b_mu, b_{lam+mu}}, each contributing one 1/4 and one 0;
      * the 3-space <P_lam, I, b_lam> contributes 1, 0, 0.

    The counts 46,575 / 47,104 / 4,600 are exactly half of the classical
    Leech inner-product census 93,150 / 94,208 / 9,200 computed in
    glm3_leech2.pair_census().
    """
    census = {0: 93150 // 2, 1: 94208 // 2, 2: 9200 // 2}
    d1 = 1
    d0 = census[0] + census[2] // 2 + 275 + 2
    dq = census[2] // 2 + 23
    d32 = census[1]
    return {"1": d1, "0": d0, "1/4": dq, "1/32": d32,
            "total": d1 + d0 + dq + d32, "expected": DIM_EVEN}


def eigen_filter(a: GriessVector, x: GriessVector,
                 values: Sequence[F]) -> GriessVector:
    """Apply prod_{lam in values} (ad_a - lam) to x."""
    y = x
    for lam in values:
        y = a.mul(y) - y.scale(lam)
    return y


def in_eigenspace(a: GriessVector, x: GriessVector,
                  values: Sequence[F]) -> bool:
    """Does x lie in the sum of the listed eigenspaces of ad_a?"""
    return eigen_filter(a, x, values).is_zero()


def _eigen_samples(cls: int, count: int = 3) -> Dict[str, List[GriessVector]]:
    """
    A spread of eigenvectors of ad(a_lam), one family per eigenvalue, built
    from the class census rather than from a numerical eigensolver.
    """
    tab = type2_table()
    lam = tab[cls]
    out: Dict[str, List[GriessVector]] = {"0": [], "1/4": [], "1/32": []}
    perp: List[Tuple[int, ...]] = []
    seen_pairs = set()
    for c, v in tab.items():
        if c == cls:
            continue
        k = abs(std_inner(lam, v))
        if k == 0:
            if len(out["0"]) < count:
                out["0"].append(b_vector(c))
            if len(perp) < count:
                perp.append(v)
        elif k == 1 and len(out["1/32"]) < count:
            out["1/32"].append(b_vector(c))
        elif k == 2 and c not in seen_pairs and len(out["1/4"]) < count:
            partner = c ^ cls
            seen_pairs.add(c)
            seen_pairs.add(partner)
            out["1/4"].append(b_vector(c) + b_vector(partner))
            out["0"].append(b_vector(c) - b_vector(partner))
        if (len(out["0"]) >= 2 * count and len(out["1/4"]) >= count
                and len(out["1/32"]) >= count and len(perp) >= count):
            break
    # A-part eigenvectors: lam w^T + w lam^T with w perp lam has eigenvalue 1/4
    for w in perp:
        M = [[F(int(lam[i]) * int(w[j]) + int(w[i]) * int(lam[j]), 8)
              for j in range(N)] for i in range(N)]
        out["1/4"].append(GriessVector(M))
    return out


# ══════════════════════════════════════════════════════════════════════════════
# §4.  FUSION
# ══════════════════════════════════════════════════════════════════════════════

#: The Monster (Ising) fusion law.  Star-products of eigenspaces land in the
#: sum of the eigenspaces listed.
FUSION_LAW: Dict[Tuple[str, str], Tuple[str, ...]] = {
    ("0", "0"): ("0",),
    ("0", "1/4"): ("1/4",),
    ("0", "1/32"): ("1/32",),
    ("1/4", "1/4"): ("1", "0"),
    ("1/4", "1/32"): ("1/32",),
    ("1/32", "1/32"): ("1", "0", "1/4"),
}

_VALUE = {"1": F(1), "0": F(0), "1/4": F(1, 4), "1/32": F(1, 32)}


def fusion_report(cls: int, count: int = 3) -> Dict[str, object]:
    """
    Verify every rule of the Monster fusion law for the axis of `cls`, on a
    spread of genuine eigenvectors.  Returns one boolean per rule.
    """
    a = axis(cls)
    samples = _eigen_samples(cls, count)
    out: Dict[str, object] = {}
    # first: the samples really are eigenvectors
    eigen_ok = True
    for name, vs in samples.items():
        for v in vs:
            if not in_eigenspace(a, v, [_VALUE[name]]):
                eigen_ok = False
    out["samples_are_eigenvectors"] = eigen_ok
    out["idempotent"] = a.mul(a) == a
    out["norm_one"] = a.form(a) == 1
    rules: Dict[str, bool] = {}
    for (p, q), targets in FUSION_LAW.items():
        vals = [_VALUE[t] for t in targets]
        ok = True
        for x in samples[p]:
            for y in samples[q]:
                if not in_eigenspace(a, x.mul(y), vals):
                    ok = False
        rules[f"{p} * {q} -> {'+'.join(targets)}"] = ok
    out["rules"] = rules
    out["all_rules_hold"] = all(rules.values())
    return out


# ══════════════════════════════════════════════════════════════════════════════
# §5.  THE GROUP ACTING:  Q = 2^(1+24) INSIDE N
# ══════════════════════════════════════════════════════════════════════════════

def miyamoto_signs(cls: int) -> Dict[str, object]:
    """
    The Miyamoto involution of the axis a_lam is +1 on V_1 + V_0 + V_{1/4}
    and -1 on V_{1/32}.  Since V_{1/32} is spanned by the b_mu with lam.mu
    odd, and lam.mu mod 2 is exactly the F_2 polar form B(lam, mu) of
    Lambda/2Lambda, the involution IS the extraspecial sign automorphism
    x_lam.  This function checks that identification on a spread of classes.
    """
    tab = type2_table()
    lam = tab[cls]
    agree = True
    checked = 0
    for c, v in tab.items():
        expected = 1 if (int(std_inner(lam, v)) % 2 == 0) else -1
        got = 1 if L2.b_form(cls, c) == 0 else -1
        if expected != got:
            agree = False
        checked += 1
        if checked >= 4000:
            break
    return {"checked": checked, "miyamoto_is_extraspecial_sign": agree}


def apply_sign_automorphism(mu: int, x: GriessVector) -> GriessVector:
    """
    The action of the extraspecial element x_mu (mu a class of
    Lambda/2Lambda) on the even algebra: trivial on A, and b_lam ->
    (-1)^B(lam, mu) b_lam.
    """
    B = {c: (k if L2.b_form(c, mu) == 0 else -k) for c, k in x.B.items()}
    return GriessVector([row[:] for row in x.A], B)


def is_automorphism_on(mu: int, vectors: Sequence[GriessVector]) -> bool:
    """g(x . y) = g(x) . g(y) on the supplied vectors."""
    for i, x in enumerate(vectors):
        for y in vectors[i:]:
            lhs = apply_sign_automorphism(mu, x.mul(y))
            rhs = apply_sign_automorphism(mu, x).mul(
                apply_sign_automorphism(mu, y))
            if lhs != rhs:
                return False
    return True


# ══════════════════════════════════════════════════════════════════════════════
# §6.  SUBALGEBRAS GENERATED BY TWO AXES  (Norton-Sakuma, computed)
# ══════════════════════════════════════════════════════════════════════════════

def _flatten(x: GriessVector, keys: Sequence[int]) -> List[F]:
    out = [x.A[i][j] for i in range(N) for j in range(i, N)]
    out.extend(x.B.get(k, F(0)) for k in keys)
    return out


def _reduce(rows: List[Tuple[int, List[F]]], w: List[F]) -> List[F]:
    for piv, r in rows:
        if w[piv]:
            c = w[piv] / r[piv]
            w = [a - c * b for a, b in zip(w, r)]
    return w


def subalgebra_closure(generators: Sequence[GriessVector],
                       max_dim: int = 24) -> List[GriessVector]:
    """
    A basis of the subalgebra generated by the given elements, computed by
    closing under the product with exact Gaussian elimination.  Raises if the
    dimension exceeds `max_dim` (the dihedral subalgebras of interest here
    are small).
    """
    basis: List[GriessVector] = []
    keys: List[int] = []
    rows: List[Tuple[int, List[F]]] = []

    def rebuild() -> None:
        nonlocal rows
        rows = []
        for e in basis:
            w = _reduce(rows, _flatten(e, keys))
            nz = next((i for i, a in enumerate(w) if a), None)
            if nz is not None:
                rows.append((nz, w))

    def add(x: GriessVector) -> bool:
        nonlocal keys
        new = [c for c in x.B if c not in keys]
        if new:
            keys = keys + sorted(new)
            rebuild()
        w = _reduce(rows, _flatten(x, keys))
        nz = next((i for i, a in enumerate(w) if a), None)
        if nz is None:
            return False
        rows.append((nz, w))
        basis.append(x)
        return True

    for g in generators:
        add(g)
    changed = True
    while changed:
        changed = False
        for i in range(len(basis)):
            for j in range(i, len(basis)):
                if add(basis[i].mul(basis[j])):
                    changed = True
                    if len(basis) > max_dim:
                        raise RuntimeError("subalgebra larger than max_dim")
                    break
            if changed:
                break
    return basis


#: dimension and axis inner product identify the three Norton-Sakuma types
#: that live in the even part.
NORTON_SAKUMA = {
    (3, F(1, 8)): "2A",
    (5, F(1, 32)): "4A",
    (2, F(0)): "2B",
}


def norton_sakuma_report(cls: Optional[int] = None) -> Dict[str, object]:
    """
    For each of the three Co_0-orbits of pairs of type-2 classes — |lam.mu|
    equal to 2, 1 or 0 — generate the subalgebra of the two axes and report
    its dimension, the inner product of the axes and the resulting
    Norton-Sakuma type.  For the 2A case the classical relation

        a_lam . a_mu = (1/8) (a_lam + a_mu - a_rho),   rho = lam + mu,

    is checked as an identity (with the sign of the third axis fixed by the
    product, which is the gauge freedom described in the module header).
    """
    tab = type2_table()
    if cls is None:
        cls = next(iter(tab))
    lam = tab[cls]
    a = axis(cls)
    found: Dict[int, int] = {}
    out: Dict[str, object] = {"orbits": {}}
    for c, v in tab.items():
        if c == cls:
            continue
        k = int(abs(std_inner(lam, v)))
        if k in found:
            continue
        found[k] = c
        b = axis(c)
        dim = len(subalgebra_closure([a, b]))
        ip = a.form(b)
        entry = {
            "inner_product": str(ip),
            "dimension": dim,
            "type": NORTON_SAKUMA.get((dim, ip), "unidentified"),
        }
        if k == 2:
            rho = cls ^ c
            lhs = a.mul(b)
            rhs = (a + b - axis(rho, -1)).scale(F(1, 8))
            entry["sakuma_2A_identity"] = lhs == rhs
        if k == 0:
            entry["product_is_zero"] = a.mul(b).is_zero()
        out["orbits"][k] = entry
        if len(found) == 3:
            break
    out["types"] = {k: out["orbits"][k]["type"] for k in sorted(out["orbits"])}
    out["all_identified"] = all(e["type"] != "unidentified"
                                for e in out["orbits"].values())
    return out


# ══════════════════════════════════════════════════════════════════════════════
# §7.  AUDIT
# ══════════════════════════════════════════════════════════════════════════════

def griess_audit(full: bool = True) -> Dict[str, object]:
    tab = type2_table()
    cls = next(iter(tab))
    a = axis(cls)
    e = identity()
    out: Dict[str, object] = {}
    out["classes"] = len(tab)
    out["dimension"] = {"A": DIM_A, "B": len(tab), "even": DIM_A + len(tab),
                        "matches": DIM_A + len(tab) == DIM_EVEN}
    out["identity_acts"] = (e.mul(a) == a and e.mul(e) == e
                            and e.mul(b_vector(cls)) == b_vector(cls))
    out["axis_idempotent"] = a.mul(a) == a
    out["axis_norm"] = str(a.form(a))
    out["axis_minus_idempotent"] = axis(cls, -1).mul(axis(cls, -1)) == axis(cls, -1)
    out["spectrum_dimensions"] = spectrum_dimensions()
    out["fusion"] = fusion_report(cls, count=2 if not full else 3)
    out["miyamoto"] = miyamoto_signs(cls)
    samples = [a, b_vector(cls), identity()]
    extra = [b_vector(c) for c in list(tab)[1:4]]
    out["extraspecial_is_automorphism"] = is_automorphism_on(
        next(iter(tab)) ^ 0b1011, samples + extra)
    # the form is Frobenius on a spread of vectors
    frob = True
    vs = samples + extra
    for i, x in enumerate(vs):
        for y in vs:
            for w in vs:
                if x.mul(y).form(w) != x.form(y.mul(w)):
                    frob = False
    out["form_is_frobenius"] = frob
    # non-associativity: exhibited on two axes that generate a 2A algebra
    partner = None
    lam = tab[cls]
    for c, v in tab.items():
        if c != cls and abs(std_inner(lam, v)) == 2:
            partner = c
            break
    b = axis(partner)
    witness = a.mul(a.mul(b)) - (a.mul(a)).mul(b)
    out["non_associative"] = not witness.is_zero()
    out["associator_norm"] = str(witness.form(witness))
    if full:
        out["norton_sakuma"] = norton_sakuma_report(cls)
    return out


def main(argv: Optional[Sequence[str]] = None) -> None:
    argv = list(argv if argv is not None else sys.argv[1:])
    full = "--quick" not in argv
    print(banner("GLM-3  GRIESS  —  the even part of the Monster algebra"))
    a = griess_audit(full=full)
    d = a["dimension"]
    print(f"\n[dimension]")
    print(f"  A = Sym^2(R^24)              : {fmt_int(d['A'])}")
    print(f"  B = type-2 classes           : {fmt_int(d['B'])}")
    print(f"  even part                    : {fmt_int(d['even'])}"
          f"  (300 + 98,280 : {d['matches']})")
    print(f"\n[axis]")
    print(f"  identity element acts        : {a['identity_acts']}")
    print(f"  a is idempotent              : {a['axis_idempotent']}")
    print(f"  (a, a)                       : {a['axis_norm']}")
    print(f"  the other sign is an axis too: {a['axis_minus_idempotent']}")
    s = a["spectrum_dimensions"]
    print(f"  eigenspace dimensions        : 1 -> {fmt_int(s['1'])}, "
          f"0 -> {fmt_int(s['0'])}, 1/4 -> {fmt_int(s['1/4'])}, "
          f"1/32 -> {fmt_int(s['1/32'])}")
    print(f"  they sum to                  : {fmt_int(s['total'])} "
          f"(expected {fmt_int(s['expected'])})")
    f = a["fusion"]
    print(f"\n[the Monster fusion law]")
    print(f"  samples are eigenvectors     : {f['samples_are_eigenvectors']}")
    for name, ok in f["rules"].items():
        print(f"    {name:28s} {ok}")
    print(f"  all rules hold               : {f['all_rules_hold']}")
    print(f"\n[the group]")
    print(f"  Miyamoto = extraspecial sign : "
          f"{a['miyamoto']['miyamoto_is_extraspecial_sign']}")
    print(f"  x_mu is an automorphism      : {a['extraspecial_is_automorphism']}")
    print(f"  the form is Frobenius        : {a['form_is_frobenius']}")
    print(f"  the algebra is non-associative: {a['non_associative']}")
    if full:
        ns = a["norton_sakuma"]
        print(f"\n[Norton-Sakuma subalgebras, computed as closures]")
        for k in sorted(ns["orbits"]):
            e = ns["orbits"][k]
            extra = ""
            if "sakuma_2A_identity" in e:
                extra = f", Sakuma identity {e['sakuma_2A_identity']}"
            if "product_is_zero" in e:
                extra = f", product zero {e['product_is_zero']}"
            print(f"  |lam.mu| = {k}: dimension {e['dimension']}, "
                  f"(a,b) = {e['inner_product']}, type {e['type']}{extra}")
    print()


if __name__ == "__main__":
    main()
