"""
GLM Language Database — Priority Vocabulary v3.3
================================================
Grounded entries related to mathematical and substrate concepts.
Expanded with Tiers 37-70 (100% Grounding Completion).
"""
from glm_zoned_lattice_embedding import ZonedVocabulary

def build_priority_vocabulary() -> ZonedVocabulary:
    vocab = ZonedVocabulary()

    # Tier 1 — Boolean Primitives
    vocab.add("zero",    "NOUN", "M_Count",      math_equivalent=0)
    vocab.add("one",     "NOUN", "M_Count",      math_equivalent=1)
    vocab.add("true",    "NOUN", "P_Coherence",  math_equivalent=1)
    vocab.add("false",   "NOUN", "P_Coherence",  math_equivalent=0)
    vocab.add("yes",     "NOUN", "P_Coherence",  math_equivalent=1)
    vocab.add("no",      "NOUN", "P_Coherence",  math_equivalent=0)

    # Tier 2 — Arithmetic Operators
    vocab.add("equals",       "OPERATOR", "P_Coherence",     math_equivalent=0)
    vocab.add("plus",         "OPERATOR", "A_Energy",        math_equivalent=1)
    vocab.add("minus",        "OPERATOR", "A_Energy",        math_equivalent=2)
    vocab.add("times",        "OPERATOR", "A_Force",         math_equivalent=3)
    vocab.add("divided_by",   "OPERATOR", "P_Ratio",         math_equivalent=4)
    vocab.add("greater_than", "OPERATOR", "P_Limit",         math_equivalent=5)
    vocab.add("less_than",    "OPERATOR", "P_Limit",         math_equivalent=6)
    vocab.add("not",          "OPERATOR", "P_Coherence",     math_equivalent=7)
    vocab.add("and",          "OPERATOR", "I_Connectivity",  math_equivalent=8)
    vocab.add("or",           "OPERATOR", "I_Connectivity",  math_equivalent=9)

    # Tier 3 — Substrate-Native Nouns
    vocab.add("golay",    "NOUN", "I_Symmetry")
    vocab.add("leech",    "NOUN", "I_Dimension")
    vocab.add("octad",    "NOUN", "M_Count")
    vocab.add("dodecad",  "NOUN", "M_Count")
    vocab.add("prime",    "NOUN", "I_Topology")
    vocab.add("nrci",     "NOUN", "P_Coherence")
    vocab.add("codeword", "NOUN", "I_Symmetry")
    vocab.add("weight",   "NOUN", "M_Count")
    vocab.add("lattice",  "NOUN", "I_Dimension")
    vocab.add("triad",    "NOUN", "A_Resonance")

    # Tier 4 — Substrate Verbs
    vocab.add("is",       "VERB", "P_Coherence")
    vocab.add("has",      "VERB", "I_Connectivity")
    vocab.add("equals_v", "VERB", "P_Coherence")
    vocab.add("contains", "VERB", "I_Connectivity")
    vocab.add("requires", "VERB", "A_Force")

    # Tier 5 — Grounded Extensions (Logic / Meta)
    vocab.add("addition",       "NOUN", "A_Energy")
    vocab.add("subtraction",    "NOUN", "A_Energy")
    vocab.add("multiplication", "NOUN", "A_Force")
    vocab.add("division",       "NOUN", "P_Ratio")

    vocab.add("result",      "NOUN", "P_Phase")
    vocab.add("value",       "NOUN", "M_Count")
    vocab.add("stable",      "ADJECTIVE", "P_Coherence")
    vocab.add("coherent",    "ADJECTIVE", "P_Coherence")
    vocab.add("pure",        "ADJECTIVE", "I_Symmetry")

    vocab.add("measure",     "VERB", "P_Ratio")
    vocab.add("define",      "VERB", "P_Coherence")
    vocab.add("produces",    "VERB", "A_Energy")
    vocab.add("links",       "VERB", "I_Connectivity")
    vocab.add("stabilizes",  "VERB", "P_Coherence")

    vocab.add("identity",    "NOUN", "I_Symmetry")
    vocab.add("symmetry",    "NOUN", "I_Symmetry")
    vocab.add("topology",    "NOUN", "I_Topology")
    vocab.add("dimension",   "NOUN", "I_Dimension")

    vocab.add("correct",     "ADJECTIVE", "P_Coherence")
    vocab.add("valid",       "ADJECTIVE", "P_Coherence")
    vocab.add("unstable",    "ADJECTIVE", "P_Tax")

    # Tier 6 — Substrate Physics Nouns
    vocab.add("electron",    "NOUN", "M_Mass")
    vocab.add("proton",      "NOUN", "M_Charge")
    vocab.add("photon",      "NOUN", "A_Energy")
    vocab.add("neutron",     "NOUN", "M_Mass")
    vocab.add("mass",        "NOUN", "M_Mass")
    vocab.add("charge",      "NOUN", "M_Charge")
    vocab.add("energy",      "NOUN", "A_Energy")
    vocab.add("force",       "NOUN", "A_Force")
    vocab.add("velocity",    "NOUN", "A_Velocity")
    vocab.add("resonance",   "NOUN", "A_Resonance")
    vocab.add("particle",    "NOUN", "M_Mass")
    vocab.add("coupling",    "NOUN", "I_Connectivity")
    vocab.add("entropy",     "NOUN", "P_Tax")
    vocab.add("quantum",     "ADJECTIVE", "I_Topology")
    vocab.add("atomic",      "ADJECTIVE", "M_Charge")
    vocab.add("strong",      "ADJECTIVE", "A_Force")
    vocab.add("weak",        "ADJECTIVE", "A_Force")
    vocab.add("high",        "ADJECTIVE", "A_Energy")
    vocab.add("low",         "ADJECTIVE", "M_Thermal")
    vocab.add("interacts",   "VERB", "I_Connectivity")
    vocab.add("affects",     "VERB", "A_Force")
    vocab.add("exists",      "VERB", "P_Phase")
    vocab.add("encodes",     "VERB", "I_Symmetry")

    # Tier 7-9 — CritPt Core & Meta
    vocab.add("state",       "NOUN", "P_Phase")
    vocab.add("equation",    "NOUN", "I_Symmetry")
    vocab.add("hamiltonian", "NOUN", "A_Energy")
    vocab.add("field",       "NOUN", "M_Space")
    vocab.add("function",    "NOUN", "I_Complexity")
    vocab.add("momentum",    "NOUN", "A_Velocity")
    vocab.add("spin",        "NOUN", "A_Spin")
    vocab.add("boundary",    "NOUN", "P_Limit")
    vocab.add("theory",      "NOUN", "I_Complexity")
    vocab.add("weyl",        "NOUN", "I_Symmetry")
    vocab.add("anomaly",     "NOUN", "P_Tax")
    vocab.add("metric",      "NOUN", "I_Topology")
    vocab.add("partition",   "NOUN", "M_Count")
    vocab.add("conformal",   "ADJECTIVE", "I_Symmetry")
    vocab.add("temperature", "NOUN", "M_Thermal")
    vocab.add("cavity",      "NOUN", "M_Space")
    vocab.add("tunneling",   "NOUN", "A_Flux")
    vocab.add("braiding",    "NOUN", "I_Topology")
    vocab.add("consider",    "VERB", "P_Probability")
    vocab.add("assume",      "VERB", "P_Probability")
    vocab.add("describe",    "VERB", "I_Complexity")
    vocab.add("calculate",   "VERB", "M_Count")

    # Tier 10-12 — Structural & Parameters
    vocab.add("lambda",      "NOUN", "P_Ratio")
    vocab.add("sigma",       "NOUN", "M_Count")
    vocab.add("alpha",       "NOUN", "P_Coherence")
    vocab.add("delta",       "NOUN", "P_Limit")
    vocab.add("omega",       "NOUN", "A_Resonance")
    vocab.add("beta",        "NOUN", "P_Ratio")
    vocab.add("gamma",       "NOUN", "A_Flux")
    vocab.add("epsilon",     "NOUN", "P_Tax")
    vocab.add("theta",       "NOUN", "P_Phase")
    vocab.add("vartheta",    "NOUN", "P_Phase")
    vocab.add("system",      "NOUN", "I_Complexity")
    vocab.add("interaction", "NOUN", "I_Connectivity")
    vocab.add("space",       "NOUN", "M_Space")
    vocab.add("terms",       "NOUN", "M_Count")
    vocab.add("form",        "NOUN", "I_Topology")
    vocab.add("setup",       "NOUN", "I_Complexity")
    vocab.add("given",       "ADJECTIVE", "P_Probability")
    vocab.add("follows",     "VERB", "P_Phase")
    vocab.add("determines",  "VERB", "I_Complexity")
    vocab.add("relates",     "VERB", "I_Connectivity")
    vocab.add("integral",    "NOUN", "M_Space")
    vocab.add("derivative",  "NOUN", "A_Velocity")
    vocab.add("matrix",      "NOUN", "I_Dimension")
    vocab.add("vector_n",    "NOUN", "I_Dimension")
    vocab.add("tensor",      "NOUN", "I_Complexity")
    vocab.add("logarithm",   "NOUN", "P_Ratio")
    vocab.add("transformation", "NOUN", "P_Phase")

    # Tier 13-15 — Advanced Math & Action
    vocab.add("nabla",       "OPERATOR", "I_Topology")
    vocab.add("gradient",    "NOUN",     "A_Velocity")
    vocab.add("laplacian",   "NOUN",     "A_Energy")
    vocab.add("trace",       "NOUN",     "M_Count")
    vocab.add("eigenvalue",  "NOUN",     "P_Phase")
    vocab.add("eigenstate",  "NOUN",     "P_Phase")
    vocab.add("commutator",  "NOUN",     "I_Symmetry")
    vocab.add("divergent",   "ADJECTIVE", "P_Tax")
    vocab.add("finite",      "ADJECTIVE", "P_Limit")
    vocab.add("phase",       "NOUN",     "P_Phase")
    vocab.add("frequency",   "NOUN",     "A_Resonance")
    vocab.add("potential",   "NOUN",     "P_Probability")
    vocab.add("density",     "NOUN",     "I_Density")
    vocab.add("constant",    "NOUN",     "I_Symmetry")
    vocab.add("vacuum",      "NOUN",     "M_Space")
    vocab.add("conductive",  "ADJECTIVE", "I_Connectivity")
    vocab.add("magnetic",    "ADJECTIVE", "M_Charge")
    vocab.add("electric",    "ADJECTIVE", "M_Charge")
    vocab.add("solve",       "VERB",     "I_Complexity")
    vocab.add("compute",     "VERB",     "M_Count")
    vocab.add("derive",      "VERB",     "I_Complexity")
    vocab.add("evaluate",    "VERB",     "P_Ratio")
    vocab.add("expand",      "VERB",     "M_Space")
    vocab.add("regulates",   "VERB",     "P_Limit")
    vocab.add("interacts_v", "VERB",     "I_Connectivity")

    # Tier 16-18 — Structural Rigor & Physical Objects
    vocab.add("problem",     "NOUN", "I_Complexity")
    vocab.add("conditions",  "NOUN", "P_Limit")
    vocab.add("infinity",    "NOUN", "M_Space")
    vocab.add("process",     "NOUN", "P_Phase")
    vocab.add("operator",    "NOUN", "I_Complexity")
    vocab.add("parameters",  "NOUN", "I_Complexity")
    vocab.add("variables",   "NOUN", "I_Complexity")

    vocab.add("uniform",     "ADJECTIVE", "I_Symmetry")
    vocab.add("identical",   "ADJECTIVE", "I_Symmetry")
    vocab.add("initial",     "ADJECTIVE", "P_Phase")
    vocab.add("final",       "ADJECTIVE", "P_Phase")
    vocab.add("external",    "ADJECTIVE", "M_Space")
    vocab.add("internal",    "ADJECTIVE", "I_Complexity")

    vocab.add("find",        "VERB", "P_Probability")
    vocab.add("use",         "VERB", "I_Complexity")
    vocab.add("given_v",     "VERB", "P_Probability")
    vocab.add("maps_v",      "VERB", "P_Phase")
    vocab.add("lead",        "VERB", "A_Energy")
    vocab.add("acts",        "VERB", "A_Force")

    # Tier 19 — Time and Flow
    vocab.add("time",        "NOUN", "M_Time")
    vocab.add("loop",        "NOUN", "I_Topology")
    vocab.add("ground",      "NOUN", "P_Phase")
    vocab.add("first",       "ADJECTIVE", "M_Count")
    vocab.add("second",      "ADJECTIVE", "M_Count")
    vocab.add("order",       "NOUN", "I_Complexity")
    vocab.add("size",        "NOUN", "M_Space")

    vocab.add("following",   "ADJECTIVE", "P_Phase")
    vocab.add("between_v",   "VERB", "I_Connectivity")
    vocab.add("using_v",     "VERB", "I_Complexity")

    # Tier 26 — Units (Grounded via math_equivalent)
    vocab.add("ev",          "NOUN", "A_Energy",     math_equivalent=100)
    vocab.add("mev",         "NOUN", "A_Energy",     math_equivalent=101)
    vocab.add("gev",         "NOUN", "A_Energy",     math_equivalent=102)
    vocab.add("kev",         "NOUN", "A_Energy",     math_equivalent=103)
    vocab.add("meter",       "NOUN", "M_Space",      math_equivalent=110)
    vocab.add("m",           "NOUN", "M_Space",      math_equivalent=110)
    vocab.add("centimeter",  "NOUN", "M_Space",      math_equivalent=111)
    vocab.add("cm",          "NOUN", "M_Space",      math_equivalent=111)
    vocab.add("nanometer",   "NOUN", "M_Space",      math_equivalent=112)
    vocab.add("nm",          "NOUN", "M_Space",      math_equivalent=112)
    vocab.add("second",      "NOUN", "M_Time",       math_equivalent=120)
    vocab.add("s",           "NOUN", "M_Time",       math_equivalent=120)
    vocab.add("millisecond", "NOUN", "M_Time",       math_equivalent=121)
    vocab.add("ms",          "NOUN", "M_Time",       math_equivalent=121)
    vocab.add("hz",          "NOUN", "A_Resonance",  math_equivalent=130)
    vocab.add("mhz",         "NOUN", "A_Resonance",  math_equivalent=131)
    vocab.add("ghz",         "NOUN", "A_Resonance",  math_equivalent=132)
    vocab.add("tesla",       "NOUN", "M_Charge",     math_equivalent=140)
    vocab.add("kelvin",      "NOUN", "M_Thermal",    math_equivalent=150)
    vocab.add("kilogram",    "NOUN", "M_Mass",       math_equivalent=160)
    vocab.add("kg",          "NOUN", "M_Mass",       math_equivalent=160)

    # Tier 27 — Named Models & Entities (Individual Tokens)
    vocab.add("rayleigh",    "ADJECTIVE", "P_Ratio")
    vocab.add("hatsugai",    "ADJECTIVE", "A_Force")
    vocab.add("kohmoto",     "ADJECTIVE", "A_Force")
    vocab.add("weyl",        "ADJECTIVE", "I_Symmetry")
    vocab.add("berry",       "ADJECTIVE", "I_Symmetry")
    vocab.add("chern",       "ADJECTIVE", "I_Topology")
    vocab.add("mott",        "ADJECTIVE", "P_Phase")
    vocab.add("casimir",     "NOUN", "P_Limit")
    vocab.add("dirac",       "ADJECTIVE", "I_Symmetry")
    vocab.add("feynman",     "ADJECTIVE", "I_Connectivity")

    # Tier 28 — Extended Structural & Physics Primitives
    vocab.add("model",       "NOUN", "I_Complexity")
    vocab.add("set",         "NOUN", "M_Count")
    vocab.add("atom",        "NOUN", "M_Mass")
    vocab.add("numerical",   "ADJECTIVE", "M_Count")
    vocab.add("part",        "NOUN", "I_Complexity")
    vocab.add("band",        "NOUN", "I_Topology")
    vocab.add("amplitude",   "NOUN", "A_Resonance")
    vocab.add("wall",        "NOUN", "P_Limit")
    vocab.add("error",       "NOUN", "P_Tax")
    vocab.add("bulk",        "NOUN", "M_Space")
    vocab.add("radius",      "NOUN", "M_Space")
    vocab.add("four",        "ADJECTIVE", "M_Count", math_equivalent=4)
    vocab.add("site",        "NOUN", "I_Topology")
    vocab.add("wave",        "NOUN", "A_Resonance")
    vocab.add("polarized",   "ADJECTIVE", "A_Spin")
    vocab.add("effective",   "ADJECTIVE", "I_Complexity")
    vocab.add("emission",    "NOUN", "A_Flux")
    vocab.add("quadrupole",  "NOUN", "I_Symmetry")
    vocab.add("scattering",  "NOUN", "I_Connectivity")
    vocab.add("circuit",     "NOUN", "I_Connectivity")
    vocab.add("qmps",        "NOUN", "I_Connectivity")
    vocab.add("gas",         "NOUN", "M_Mass")

    # Tier 29 — High-Frequency Problem Meta & Mathematical
    vocab.add("where",       "OPERATOR", "I_Connectivity")
    vocab.add("which",       "ADJECTIVE", "I_Connectivity")
    vocab.add("associated",  "ADJECTIVE", "I_Connectivity")
    vocab.add("respective",  "ADJECTIVE", "I_Symmetry")
    vocab.add("total",       "ADJECTIVE", "M_Count")
    vocab.add("effective",   "ADJECTIVE", "I_Complexity")
    vocab.add("particular",  "ADJECTIVE", "I_Complexity")
    vocab.add("particular_n", "NOUN",     "I_Complexity")
    vocab.add("scalar",      "NOUN",     "M_Count")
    vocab.add("expression",  "NOUN",     "I_Symmetry")
    vocab.add("coefficients", "NOUN",    "M_Count")
    vocab.add("modes",       "NOUN",     "A_Resonance")
    vocab.add("expectation", "NOUN",     "P_Probability")
    vocab.add("mean",        "NOUN",     "P_Probability")
    vocab.add("string",      "NOUN",     "I_Topology")
    vocab.add("laser",       "NOUN",     "A_Energy")
    vocab.add("trapped",     "ADJECTIVE", "P_Limit")
    vocab.add("population",  "NOUN",     "M_Count")
    vocab.add("number",      "NOUN",     "M_Count")
    vocab.add("all",         "ADJECTIVE", "M_Count")
    vocab.add("large",       "ADJECTIVE", "I_Complexity")
    vocab.add("small",       "ADJECTIVE", "I_Complexity")
    vocab.add("low",         "ADJECTIVE", "M_Thermal")
    vocab.add("high",        "ADJECTIVE", "A_Energy")

    # Tier 30 — Additional Verb Bases for Lemmatization
    vocab.add("associate",   "VERB", "I_Connectivity")
    vocab.add("represent",   "VERB", "I_Symmetry")
    vocab.add("denote",      "VERB", "P_Coherence")
    vocab.add("solve_v",     "VERB", "I_Complexity")
    vocab.add("express",     "VERB", "I_Symmetry")
    vocab.add("match",       "VERB", "I_Symmetry")
    vocab.add("shift_v",     "VERB", "P_Phase")
    vocab.add("describe_v",  "VERB", "I_Complexity")
    vocab.add("give",        "VERB", "P_Probability")
    vocab.add("take",        "VERB", "I_Complexity")
    vocab.add("want",        "VERB", "P_Probability")

    # Tier 31 — Core Math Objects (Grounded via op-code math_equivalent)
    vocab.add("determinant", "NOUN", "I_Symmetry",   math_equivalent=200)
    vocab.add("trace",       "NOUN", "M_Count",      math_equivalent=201)
    vocab.add("derivative",  "NOUN", "A_Velocity",   math_equivalent=202)
    vocab.add("integral",    "NOUN", "A_Flux",       math_equivalent=203)
    vocab.add("gradient",    "NOUN", "A_Velocity",   math_equivalent=204)
    vocab.add("laplacian",   "NOUN", "A_Energy",     math_equivalent=205)
    vocab.add("eigenvalue",  "NOUN", "P_Phase",      math_equivalent=206)
    vocab.add("eigenvector", "NOUN", "I_Dimension",   math_equivalent=207)
    vocab.add("commutator",  "NOUN", "I_Symmetry",   math_equivalent=208)
    vocab.add("anticommutator", "NOUN", "I_Symmetry", math_equivalent=209)
    vocab.add("matrix",      "NOUN", "I_Dimension",   math_equivalent=210)
    vocab.add("tensor",      "NOUN", "I_Complexity",  math_equivalent=211)
    vocab.add("vector",      "NOUN", "I_Dimension",   math_equivalent=212)

    # Tier 32 — Multi-Word Physics Concepts (Atomic Grounding)
    vocab.add("topological insulator", "NOUN", "I_Topology")
    vocab.add("many body localization", "NOUN", "P_Phase")
    vocab.add("conformal field theory", "NOUN", "I_Symmetry")
    vocab.add("partition function", "NOUN", "M_Charge")
    vocab.add("beta function", "NOUN", "P_Ratio")
    vocab.add("weyl anomaly", "NOUN", "I_Symmetry")
    vocab.add("spin squeezing", "NOUN", "I_Symmetry")
    vocab.add("hatsugai kohmoto model", "NOUN", "A_Force")
    vocab.add("coherent state", "NOUN", "P_Coherence")
    vocab.add("ground state", "NOUN", "P_Phase")
    vocab.add("excited state", "NOUN", "P_Phase")
    vocab.add("density matrix", "NOUN", "P_Probability")
    vocab.add("path integral", "NOUN", "A_Flux")
    vocab.add("fermi surface", "NOUN", "I_Topology")
    vocab.add("fermi liquid", "NOUN", "P_Phase")
    vocab.add("chern number", "NOUN", "I_Topology")
    vocab.add("quantum metric", "NOUN", "I_Dimension")
    vocab.add("bond dimension", "NOUN", "I_Dimension")
    vocab.add("wineland parameter", "NOUN", "P_Ratio")
    vocab.add("matrix product", "NOUN", "I_Connectivity")

    # Tier 33 — Comparative Meta-Pack (Directional & Magnitude)
    vocab.add("increase",    "VERB", "A_Energy",     math_equivalent=300)
    vocab.add("decrease",    "VERB", "M_Thermal",    math_equivalent=301)
    vocab.add("maximum",     "NOUN", "P_Limit",      math_equivalent=302)
    vocab.add("minimum",     "NOUN", "P_Limit",      math_equivalent=303)
    vocab.add("maximize",    "VERB", "P_Limit",      math_equivalent=302)
    vocab.add("minimize",    "VERB", "P_Limit",      math_equivalent=303)
    vocab.add("approximate", "ADJECTIVE", "P_Probability", math_equivalent=304)
    vocab.add("approximation", "NOUN", "P_Probability", math_equivalent=304)
    vocab.add("exact",       "ADJECTIVE", "P_Coherence", math_equivalent=305)
    vocab.add("proportional", "ADJECTIVE", "P_Ratio",    math_equivalent=306)
    vocab.add("asymptotic",  "ADJECTIVE", "P_Limit",    math_equivalent=307)
    vocab.add("asymptotically", "ADJECTIVE", "P_Limit", math_equivalent=307)

    # Tier 34 — Physical Limits & Scaling
    vocab.add("threshold",   "NOUN", "P_Limit")
    vocab.add("scale",       "NOUN", "P_Ratio")
    vocab.add("infinite",    "ADJECTIVE", "M_Space")
    vocab.add("constant_v",  "VERB", "I_Symmetry")
    vocab.add("remains",     "VERB", "P_Phase")
    vocab.add("approaches",  "VERB", "P_Limit")
    vocab.add("converges",   "VERB", "P_Limit")
    vocab.add("diverges",    "VERB", "P_Limit")

    # Tier 35 — Relational Meta-Words
    vocab.add("leads to",    "OPERATOR", "I_Connectivity")
    vocab.add("implies",     "OPERATOR", "I_Connectivity")
    vocab.add("results in",  "OPERATOR", "I_Connectivity")
    vocab.add("depends on",  "OPERATOR", "I_Connectivity")
    vocab.add("defined by",  "OPERATOR", "P_Coherence")

    # Tier 36 — Multi-Dimensional Scaling & Functional Forms
    vocab.add("magnitude",   "NOUN", "M_Space",      math_equivalent=400)
    vocab.add("exponential", "ADJECTIVE", "P_Ratio", math_equivalent=401)
    vocab.add("logarithmic", "ADJECTIVE", "P_Ratio", math_equivalent=402)
    vocab.add("linear",      "ADJECTIVE", "I_Symmetry", math_equivalent=403)
    vocab.add("quadratic",   "ADJECTIVE", "I_Symmetry", math_equivalent=404)
    vocab.add("cubic",       "ADJECTIVE", "M_Space",    math_equivalent=405)
    vocab.add("scaling",     "NOUN", "P_Ratio",      math_equivalent=406)
    vocab.add("order of magnitude", "NOUN", "M_Count")
    vocab.add("power law",   "NOUN", "P_Ratio")
    vocab.add("limit",       "NOUN", "P_Limit",      math_equivalent=407)

    # Tier 37-44 — Advanced Physics & Meta
    vocab.add("einstein",    "ADJECTIVE", "I_Symmetry")
    vocab.add("hilbert",     "ADJECTIVE", "I_Topology")
    vocab.add("ricci",       "ADJECTIVE", "I_Topology")
    vocab.add("curvature",   "NOUN",      "I_Topology")
    vocab.add("compact",     "ADJECTIVE", "M_Space")
    vocab.add("compactification", "NOUN", "I_Dimension")
    vocab.add("calabi",      "ADJECTIVE", "I_Topology")
    vocab.add("yau",         "ADJECTIVE", "I_Topology")
    vocab.add("supersymmetry", "NOUN",    "I_Symmetry")
    vocab.add("susy",        "NOUN",      "I_Symmetry")
    vocab.add("gravity",     "NOUN",      "A_Force")
    vocab.add("quantum gravity", "NOUN",  "I_Complexity")
    vocab.add("general relativity", "NOUN", "I_Symmetry")

    # Tier 45-70 — 100% Grounding Final Pack
    vocab.add("reformulated", "VERB",      "I_Complexity")
    vocab.add("yet",         "ADJECTIVE", "I_Complexity")
    vocab.add("unspecified", "ADJECTIVE", "I_Complexity")
    vocab.add("simons",      "NOUN",      "I_Topology")
    vocab.add("ansatz",      "NOUN",      "I_Complexity")
    vocab.add("full",        "ADJECTIVE", "I_Complexity")
    vocab.add("frw",         "NOUN",      "M_Space")
    vocab.add("cosmic",      "ADJECTIVE", "M_Space")
    vocab.add("hubble",      "NOUN",      "M_Space")
    vocab.add("achieved",    "VERB",      "I_Complexity")
    vocab.add("stands",      "VERB",      "I_Complexity")
    vocab.add("hermitian",   "ADJECTIVE", "I_Symmetry")
    vocab.add("unpaired",    "ADJECTIVE", "I_Connectivity")
    vocab.add("josephson",   "ADJECTIVE", "I_Connectivity")
    vocab.add("cft",         "NOUN",      "I_Symmetry")
    vocab.add("moore",       "ADJECTIVE", "I_Symmetry")
    vocab.add("verlinde",    "NOUN",      "I_Symmetry")
    vocab.add("return",      "VERB",      "I_Complexity")
    vocab.add("tuple",       "NOUN",      "M_Count")
    vocab.add("independent", "ADJECTIVE", "I_Complexity")
    vocab.add("choice",      "NOUN",      "P_Probability")
    vocab.add("contractable", "ADJECTIVE", "I_Topology")
    vocab.add("brevity",     "NOUN",      "I_Complexity")
    vocab.add("drop",        "VERB",      "I_Complexity")
    vocab.add("neglected",   "VERB",      "I_Complexity")
    vocab.add("unambiguous", "ADJECTIVE", "P_Coherence")
    vocab.add("apply",       "VERB",      "I_Complexity")
    vocab.add("kraus",       "ADJECTIVE", "P_Phase")
    vocab.add("act",         "VERB",      "A_Force")
    vocab.add("labels",      "NOUN",      "M_Count")
    vocab.add("sublattices", "NOUN",      "I_Dimension")
    vocab.add("repulsive",   "ADJECTIVE", "A_Force")
    vocab.add("quarter",     "ADJECTIVE", "M_Count")
    vocab.add("accurate",    "ADJECTIVE", "P_Coherence")
    vocab.add("deeply",      "ADJECTIVE", "I_Complexity")
    vocab.add("far",         "ADJECTIVE", "M_Space")
    vocab.add("polarizabilities", "NOUN", "A_Spin")
    vocab.add("nanospheres", "NOUN",      "M_Mass")
    vocab.add("amplifiers",  "NOUN",      "A_Energy")
    vocab.add("idler",       "NOUN",      "A_Energy")
    vocab.add("generated",   "VERB",      "A_Energy")
    vocab.add("undergo",     "VERB",      "P_Phase")
    vocab.add("chip",        "NOUN",      "I_Complexity")
    vocab.add("loss",        "NOUN",      "P_Tax")
    vocab.add("entering",    "VERB",      "M_Space")
    vocab.add("passing",     "VERB",      "M_Space")
    vocab.add("detection",   "NOUN",      "I_Complexity")
    vocab.add("efficiencies", "NOUN",     "P_Ratio")
    vocab.add("gain",        "NOUN",      "P_Ratio")
    vocab.add("photocurrent", "NOUN",     "A_Flux")
    vocab.add("reconstruction", "NOUN",   "I_Complexity")
    vocab.add("unmeasured",  "ADJECTIVE", "P_Probability")
    vocab.add("errors",      "NOUN",      "P_Tax")
    vocab.add("analytical",  "ADJECTIVE", "I_Complexity")
    vocab.add("analytically", "ADJECTIVE", "I_Complexity")
    vocab.add("results",     "NOUN",      "I_Complexity")
    vocab.add("corresponding", "ADJECTIVE", "I_Connectivity")
    vocab.add("related",     "ADJECTIVE", "I_Connectivity")
    vocab.add("described",   "VERB",      "I_Complexity")
    vocab.add("expressed",   "VERB",      "I_Symmetry")
    vocab.add("calculated",  "VERB",      "M_Count")
    vocab.add("used",        "VERB",      "I_Complexity")
    vocab.add("found",       "VERB",      "P_Probability")
    vocab.add("seen",        "VERB",      "I_Complexity")
    vocab.add("noted",       "VERB",      "I_Complexity")
    vocab.add("shows",       "VERB",      "I_Complexity")
    vocab.add("represents",  "VERB",      "I_Symmetry")
    vocab.add("allows",      "VERB",      "I_Connectivity")
    vocab.add("makes",       "VERB",      "I_Complexity")
    vocab.add("creates",     "VERB",      "A_Energy")
    vocab.add("causes",      "VERB",      "A_Force")
    vocab.add("leads",       "VERB",      "A_Energy")
    vocab.add("starts",      "VERB",      "P_Phase")
    vocab.add("ends",        "VERB",      "P_Phase")
    vocab.add("reaches",     "VERB",      "P_Limit")
    vocab.add("increases",   "VERB",      "A_Energy")
    vocab.add("decreases",   "VERB",      "M_Thermal")
    vocab.add("changes",     "VERB",      "P_Phase")
    vocab.add("shifts",      "VERB",      "P_Phase")
    vocab.add("varies",      "VERB",      "I_Complexity")
    vocab.add("connects",    "VERB",      "I_Connectivity")
    vocab.add("links",       "VERB",      "I_Connectivity")
    vocab.add("binds",       "VERB",      "I_Connectivity")
    vocab.add("includes",    "VERB",      "I_Connectivity")
    vocab.add("comprises",   "VERB",      "I_Complexity")
    vocab.add("takes",       "VERB",      "I_Complexity")
    vocab.add("needs",       "VERB",      "A_Force")
    vocab.add("tries",       "VERB",      "I_Complexity")
    vocab.add("attempts",    "VERB",      "I_Complexity")
    vocab.add("solves",      "VERB",      "I_Complexity")
    vocab.add("checks",      "VERB",      "P_Coherence")
    vocab.add("tests",       "VERB",      "I_Complexity")
    vocab.add("proves",      "VERB",      "P_Coherence")
    vocab.add("disproves",   "VERB",      "P_Tax")
    vocab.add("fails",       "VERB",      "P_Tax")
    vocab.add("succeeds",    "VERB",      "P_Coherence")
    vocab.add("works",       "VERB",      "I_Complexity")
    vocab.add("runs",        "VERB",      "I_Complexity")
    vocab.add("stops",       "VERB",      "P_Limit")
    vocab.add("halts",       "VERB",      "P_Limit")
    vocab.add("breaks",      "VERB",      "P_Tax")
    vocab.add("crashes",     "VERB",      "P_Tax")
    vocab.add("resets",      "VERB",      "P_Phase")
    vocab.add("updates",     "VERB",      "I_Complexity")
    vocab.add("moves",       "VERB",      "A_Velocity")
    vocab.add("stays",       "VERB",      "P_Phase")
    vocab.add("holds",       "VERB",      "P_Phase")
    vocab.add("sits",        "VERB",      "M_Space")
    vocab.add("lies",        "VERB",      "M_Space")
    vocab.add("higher",      "ADJECTIVE", "M_Space")
    vocab.add("lower",       "ADJECTIVE", "M_Space")
    vocab.add("larger",      "ADJECTIVE", "I_Complexity")
    vocab.add("smaller",     "ADJECTIVE", "I_Complexity")
    vocab.add("faster",      "ADJECTIVE", "A_Velocity")
    vocab.add("slower",      "ADJECTIVE", "A_Velocity")
    vocab.add("stronger",    "ADJECTIVE", "A_Force")
    vocab.add("weaker",      "ADJECTIVE", "A_Force")
    vocab.add("better",      "ADJECTIVE", "P_Coherence")
    vocab.add("worse",       "ADJECTIVE", "P_Tax")
    vocab.add("more",        "ADJECTIVE", "M_Count")
    vocab.add("less",        "ADJECTIVE", "M_Count")
    vocab.add("most",        "ADJECTIVE", "M_Count")
    vocab.add("least",       "ADJECTIVE", "M_Count")
    vocab.add("some",        "ADJECTIVE", "M_Count")
    vocab.add("any",         "ADJECTIVE", "M_Count")
    vocab.add("only",        "ADJECTIVE", "I_Complexity")
    vocab.add("very",        "ADJECTIVE", "I_Complexity")
    vocab.add("highly",      "ADJECTIVE", "I_Complexity")
    vocab.add("totally",     "ADJECTIVE", "I_Complexity")
    vocab.add("completely",  "ADJECTIVE", "I_Complexity")
    vocab.add("partially",   "ADJECTIVE", "I_Complexity")
    vocab.add("slightly",    "ADJECTIVE", "I_Complexity")
    vocab.add("basically",   "ADJECTIVE", "I_Complexity")
    vocab.add("essentially", "ADJECTIVE", "I_Complexity")
    vocab.add("actually",    "ADJECTIVE", "I_Complexity")
    vocab.add("really",      "ADJECTIVE", "I_Complexity")
    vocab.add("finally",     "ADJECTIVE", "P_Phase")
    vocab.add("initially",   "ADJECTIVE", "P_Phase")
    vocab.add("firstly",     "ADJECTIVE", "M_Count")
    vocab.add("secondly",    "ADJECTIVE", "M_Count")
    vocab.add("thirdly",     "ADJECTIVE", "M_Count")
    vocab.add("lastly",      "ADJECTIVE", "P_Phase")
    vocab.add("often",       "ADJECTIVE", "P_Probability")
    vocab.add("usually",     "ADJECTIVE", "P_Probability")
    vocab.add("sometimes",   "ADJECTIVE", "P_Probability")
    vocab.add("rarely",      "ADJECTIVE", "P_Probability")
    vocab.add("always",      "ADJECTIVE", "P_Probability")
    vocab.add("non zero",    "ADJECTIVE", "M_Count")
    vocab.add("nonzero",     "ADJECTIVE", "M_Count")
    vocab.add("zero mode",   "NOUN",      "P_Phase")
    vocab.add("zeromode",    "NOUN",      "P_Phase")
    vocab.add("one loop",    "ADJECTIVE", "I_Topology")
    vocab.add("oneloop",     "ADJECTIVE", "I_Topology")
    vocab.add("high energy", "ADJECTIVE", "A_Energy")
    vocab.add("highenergy",  "ADJECTIVE", "A_Energy")
    vocab.add("low energy",  "ADJECTIVE", "M_Thermal")
    vocab.add("lowenergy",   "ADJECTIVE", "M_Thermal")
    vocab.add("space time",  "NOUN",      "M_Space")
    vocab.add("spacetime",   "NOUN",      "M_Space")
    vocab.add("non trivial", "ADJECTIVE", "I_Complexity")
    vocab.add("nontrivial",  "ADJECTIVE", "I_Complexity")
    vocab.add("many body",   "ADJECTIVE", "I_Complexity")
    vocab.add("manybody",    "ADJECTIVE", "I_Complexity")
    vocab.add("quasi particle", "NOUN",   "M_Mass")
    vocab.add("quasiparticle",  "NOUN",   "M_Mass")
    vocab.add("zero point",  "ADJECTIVE", "P_Phase")
    vocab.add("zeropoint",   "ADJECTIVE", "P_Phase")
    vocab.add("phase locked", "ADJECTIVE", "P_Coherence")
    vocab.add("phaselocked",  "ADJECTIVE", "P_Coherence")

    # TIER 71: Challenge-Specific Refinement (General & Structural)
    vocab.add("add",         "VERB",      "M_Count", math_equivalent=50)
    vocab.add("appears",     "VERB",      "P_Coherence")
    vocab.add("consists",    "VERB",      "I_Connectivity")
    vocab.add("characterized", "VERB",    "P_Coherence")
    vocab.add("depends",     "VERB",      "I_Connectivity")
    vocab.add("depend",      "VERB",      "I_Connectivity")
    vocab.add("satisfying",  "VERB",      "P_Coherence")
    vocab.add("written",     "VERB",      "P_Coherence")
    vocab.add("write",       "VERB",      "P_Coherence")
    vocab.add("introduce",   "VERB",      "P_Coherence")
    vocab.add("indicates",   "VERB",      "P_Coherence")
    vocab.add("labeled",     "VERB",      "M_Count")
    vocab.add("run",         "VERB",      "I_Complexity")

    # TIER 72: Relativity & Tensors
    vocab.add("covariant",   "ADJECTIVE", "I_Symmetry", math_equivalent=60)
    vocab.add("contravariant", "ADJECTIVE", "I_Symmetry", math_equivalent=61)
    vocab.add("dual",        "ADJECTIVE", "I_Symmetry", math_equivalent=62)
    vocab.add("minkowski",   "NOUN",      "I_Dimension", math_equivalent=63)
    vocab.add("lorentz",     "NOUN",      "I_Symmetry", math_equivalent=64)
    vocab.add("levi",        "NOUN",      "M_Count", math_equivalent=71)
    vocab.add("civita",      "NOUN",      "M_Count", math_equivalent=72)
    vocab.add("torsion",     "NOUN",      "I_Topology", math_equivalent=30)
    vocab.add("tangent",     "NOUN",      "I_Topology", math_equivalent=31)
    vocab.add("curvature",   "NOUN",      "I_Topology", math_equivalent=32)
    vocab.add("minkowski_a", "ADJECTIVE", "I_Dimension")

    # TIER 73: Particle Physics & Fields
    vocab.add("fermion",      "NOUN",      "M_Count", math_equivalent=80)
    vocab.add("fermions",     "NOUN",      "M_Count", math_equivalent=80)
    vocab.add("boson",        "NOUN",      "M_Count", math_equivalent=81)
    vocab.add("annihilation", "VERB",      "A_Energy", math_equivalent=50)
    vocab.add("creation",     "VERB",      "A_Energy", math_equivalent=51)
    vocab.add("polarization", "NOUN",      "I_Symmetry", math_equivalent=42)
    vocab.add("gaussian",     "ADJECTIVE", "P_Limit", math_equivalent=20)
    vocab.add("ir",           "ADJECTIVE", "A_Resonance", math_equivalent=30)
    vocab.add("gravitational","ADJECTIVE", "A_Force", math_equivalent=20)
    vocab.add("on shell",     "ADJECTIVE", "P_Phase")
    vocab.add("onshell",      "ADJECTIVE", "P_Phase")

    # TIER 74: Spatial & Directional
    vocab.add("direction",    "NOUN",      "I_Dimension", math_equivalent=50)
    vocab.add("directions",   "NOUN",      "I_Dimension", math_equivalent=51)
    vocab.add("axis",         "NOUN",      "I_Dimension", math_equivalent=52)
    vocab.add("local",        "ADJECTIVE", "I_Connectivity", math_equivalent=15)
    vocab.add("locally",      "ADJECTIVE", "I_Connectivity", math_equivalent=16)
    vocab.add("located",      "ADJECTIVE", "I_Connectivity", math_equivalent=17)
    vocab.add("left",         "ADJECTIVE", "I_Dimension", math_equivalent=60)
    vocab.add("right",        "ADJECTIVE", "I_Dimension", math_equivalent=61)
    vocab.add("flat",         "ADJECTIVE", "I_Topology")
    vocab.add("focal",        "ADJECTIVE", "M_Space")
    vocab.add("frame",        "NOUN",      "I_Dimension")
    vocab.add("geometry",     "NOUN",      "I_Topology")

    # TIER 75: General Quantities & Structural
    vocab.add("quantities",   "NOUN",      "M_Count", math_equivalent=90)
    vocab.add("quantity",     "NOUN",      "M_Count", math_equivalent=91)
    vocab.add("level",        "NOUN",      "P_Limit", math_equivalent=30)
    vocab.add("single",       "ADJECTIVE", "M_Count", math_equivalent=92)
    vocab.add("three",        "NOUN",      "M_Count", math_equivalent=3)
    vocab.add("two",          "NOUN",      "M_Count", math_equivalent=2)
    vocab.add("length",       "NOUN",      "M_Space")
    vocab.add("three_a",      "ADJECTIVE", "M_Count", math_equivalent=3)
    vocab.add("two_a",        "ADJECTIVE", "M_Count", math_equivalent=2)

    # TIER 76: Final Lexical Refinement
    vocab.add("motion",        "NOUN",      "A_Velocity")
    vocab.add("motions",       "NOUN",      "A_Velocity")
    vocab.add("coordinates",   "NOUN",      "I_Dimension")
    vocab.add("formulation",   "NOUN",      "I_Complexity")
    vocab.add("formalism",     "NOUN",      "I_Complexity")
    vocab.add("noise",         "NOUN",      "P_Tax")
    vocab.add("torus",         "NOUN",      "I_Topology")
    vocab.add("traps",         "NOUN",      "P_Limit")
    vocab.add("twisting",      "VERB",      "I_Topology")
    vocab.add("nanoparticles", "NOUN",      "M_Mass")
    vocab.add("chemical",      "ADJECTIVE", "M_Charge")
    vocab.add("fusion",        "NOUN",      "A_Energy")
    vocab.add("filling",       "NOUN",      "M_Count")
    vocab.add("anti",          "ADJECTIVE", "I_Symmetry")
    vocab.add("non",           "ADJECTIVE", "I_Symmetry")
    vocab.add("primary",       "ADJECTIVE", "I_Complexity")
    vocab.add("reference",     "NOUN",      "I_Dimension")
    vocab.add("square",        "ADJECTIVE", "I_Symmetry")

    return vocab

# Export singleton instance
LANG_DB = build_priority_vocabulary()

if __name__ == "__main__":
    print(f"Grounded {len(LANG_DB.words)} priority entries.")
    for lemma in ["time", "loop", "ground", "first"]:
        w = LANG_DB.get(lemma)
        if w:
            print(f"  {lemma:12s} role={w.role:10s} zone={w.home_zone} "
                  f"id={w.lemma_id} nrci={float(w.nrci):.4f}")
