#!/usr/bin/env python3
"""
UBP Core: First Principles Library
===================================

This module consolidates:
1. Golay G₂₄ Error-Correction Code (24-bit perfect code)
2. UBP/OffBit Engine (Universal Binary Principle)

Pure Python implementation with NO external dependencies (no numpy, no pandas).

# Euan Craig, New Zealand - this version Generated by K-Dense
# 11 December 2025
# https://github.com/DigitalEuan/UBP_Repo/first_principles_drug_discovery_campaign
"""

import math
import random
from typing import Tuple, List, Optional, Iterable
from fractions import Fraction
from decimal import Decimal, getcontext
from dataclasses import dataclass

# ===================================================================
# SECTION 1: MATRIX HELPER FUNCTIONS (Pure Python)
# ===================================================================

def identity_matrix(n: int) -> List[List[int]]:
    """Create n×n identity matrix."""
    return [[1 if i == j else 0 for j in range(n)] for i in range(n)]


def hstack_matrices(A: List[List[int]], B: List[List[int]]) -> List[List[int]]:
    """Horizontally stack two matrices [A | B]."""
    assert len(A) == len(B), "Matrices must have same number of rows"
    return [row_a + row_b for row_a, row_b in zip(A, B)]


def get_matrix_transpose(A: List[List[int]]) -> List[List[int]]:
    """Transpose matrix A."""
    if not A:
        return []
    return [[A[i][j] for i in range(len(A))] for j in range(len(A[0]))]


def matrix_multiply_binary(A: List[List[int]], B: List[List[int]]) -> List[List[int]]:
    """
    Multiply two matrices in binary (mod 2) arithmetic.

    Args:
        A: Matrix of shape (m, n)
        B: Matrix of shape (n, p)

    Returns:
        Result matrix of shape (m, p) with all elements mod 2
    """
    if not A or not B:
        return []

    m, n = len(A), len(A[0])
    n2, p = len(B), len(B[0])

    assert n == n2, f"Matrix dimensions don't match: ({m},{n}) × ({n2},{p})"

    result = []
    for i in range(m):
        row = []
        for j in range(p):
            # Dot product of A[i,:] and B[:,j], mod 2
            val = sum(A[i][k] * B[k][j] for k in range(n)) % 2
            row.append(val)
        result.append(row)

    return result


def are_matrices_equal_binary(A: List[List[int]], B: List[List[int]]) -> bool:
    """Check if two matrices are equal (element-wise)."""
    if len(A) != len(B):
        return False
    for row_a, row_b in zip(A, B):
        if len(row_a) != len(row_b):
            return False
        if row_a != row_b:
            return False
    return True


# ===================================================================
# SECTION 2: GOLAY G₂₄ ERROR-CORRECTION CODE
# ===================================================================

# The 12×12 matrix A for Golay G₂₄ (using hexacode construction)
A_MATRIX = [
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
    [1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1],
    [1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1],
    [1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1],
    [1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1],
    [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1],
    [1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1],
    [1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1],
    [1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0],
    [1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1],
    [1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0],
    [0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1]
]

# Generator matrix G = [I₁₂ | A]
I_12 = identity_matrix(12)
G_MATRIX = hstack_matrices(I_12, A_MATRIX)

# Parity-check matrix H = [A^T | I₁₂]
H_MATRIX = hstack_matrices(get_matrix_transpose(A_MATRIX), I_12)


def build_syndrome_table() -> dict:
    """
    Build syndrome lookup table for error correction.

    Returns:
        Dictionary {syndrome_tuple: error_pattern_list}
    """
    syndrome_table = {}
    n = 24

    # Weight 0 (no errors)
    e = [0] * n
    syndrome_matrix = matrix_multiply_binary(H_MATRIX, [[bit] for bit in e])
    syndrome = tuple([row[0] for row in syndrome_matrix])
    syndrome_table[syndrome] = list(e)

    # Weight 1 (single-bit errors)
    for i in range(n):
        e = [0] * n
        e[i] = 1
        syndrome_matrix = matrix_multiply_binary(H_MATRIX, [[bit] for bit in e])
        syndrome = tuple([row[0] for row in syndrome_matrix])
        syndrome_table[syndrome] = list(e)

    # Weight 2 (two-bit errors)
    for i in range(n):
        for j in range(i+1, n):
            e = [0] * n
            e[i] = 1
            e[j] = 1
            syndrome_matrix = matrix_multiply_binary(H_MATRIX, [[bit] for bit in e])
            syndrome = tuple([row[0] for row in syndrome_matrix])
            if syndrome not in syndrome_table:
                syndrome_table[syndrome] = list(e)

    # Weight 3 (three-bit errors)
    for i in range(n):
        for j in range(i+1, n):
            for k in range(j+1, n):
                e = [0] * n
                e[i] = 1
                e[j] = 1
                e[k] = 1
                syndrome_matrix = matrix_multiply_binary(H_MATRIX, [[bit] for bit in e])
                syndrome = tuple([row[0] for row in syndrome_matrix])
                if syndrome not in syndrome_table:
                    syndrome_table[syndrome] = list(e)

    return syndrome_table


# Build syndrome table (cached)
SYNDROME_TABLE = build_syndrome_table()


def golay_encode(message: List[int]) -> List[int]:
    """
    Encode a 12-bit message into a 24-bit Golay codeword.

    Args:
        message: 12-bit binary list

    Returns:
        24-bit codeword list
    """
    assert len(message) == 12, "Message must be 12 bits"
    codeword = matrix_multiply_binary([message], G_MATRIX)[0]
    return codeword


def golay_decode(received: List[int]) -> Tuple[List[int], int, bool]:
    """
    Decode a received 24-bit word, correcting up to 3 errors.

    Args:
        received: 24-bit received word (possibly with errors)

    Returns:
        (decoded_message, num_errors_corrected, success)
    """
    assert len(received) == 24, "Received word must be 24 bits"

    # Compute syndrome
    syndrome_matrix = matrix_multiply_binary(H_MATRIX, [[bit] for bit in received])
    syndrome_tuple = tuple([row[0] for row in syndrome_matrix])

    # Look up error pattern
    if syndrome_tuple in SYNDROME_TABLE:
        error_pattern = SYNDROME_TABLE[syndrome_tuple]
        corrected = [(r + e) % 2 for r, e in zip(received, error_pattern)]
        num_errors = sum(error_pattern)

        # Extract message (first 12 bits in standard form)
        decoded_message = corrected[:12]

        return decoded_message, num_errors, True
    else:
        # More than 3 errors - cannot correct
        decoded_message = received[:12]
        return decoded_message, -1, False


class GolayCodeword:
    """Represents a Golay G₂₄ codeword."""

    def __init__(self, bits: List[int]) -> None:
        assert len(bits) == 24, "Golay codeword must be 24 bits"
        self.bits = bits

    def __repr__(self) -> str:
        bit_str = ''.join(str(b) for b in self.bits)
        return f"GolayCodeword({bit_str[:12]}|{bit_str[12:]})"

    def hamming_weight(self) -> int:
        """Return the Hamming weight (number of 1s)."""
        return sum(self.bits)

    def hamming_distance(self, other: 'GolayCodeword') -> int:
        """Compute Hamming distance to another codeword."""
        return sum(1 for b1, b2 in zip(self.bits, other.bits) if b1 != b2)


# ===================================================================
# SECTION 3: UBP/OFFBIT ENGINE
# ===================================================================

# Decimal precision setup for π-derived constants
getcontext().prec = 60

PI_D = Decimal(str(math.pi))
Y_D = PI_D / (PI_D ** 2 + Decimal(2))  # Y = π / (π^2 + 2)
Y_INV_D = PI_D + Decimal(2) / PI_D     # Algebraic inverse form
ONE = Fraction(1, 1)


def bits_to_int(bits: Iterable[int]) -> int:
    """Convert bit sequence to integer."""
    out = 0
    for b in bits:
        out = (out << 1) | (1 if b else 0)
    return out


def int_to_bits(x: int, width: int) -> List[int]:
    """Convert integer to bit list of specified width."""
    return [(x >> i) & 1 for i in reversed(range(width))]


def hamming(a: int, b: int) -> int:
    """Compute Hamming distance between two integers."""
    return bin(a ^ b).count("1")


@dataclass
class OffBit:
    """
    OffBit: The fundamental information primitive.

    Represents a fixed-width binary state that can be rotated,
    analyzed for parity, and transformed into observable signatures.
    """
    width: int
    bits: int  # Stored as integer for efficient operations

    @classmethod
    def from_int(cls, width: int, value: int):
        """Create OffBit from integer value with specified width."""
        mask = (1 << width) - 1
        return cls(width=width, bits=value & mask)

    @classmethod
    def from_bits_list(cls, bits_list: List[int]):
        """Create OffBit from list of bits."""
        return cls(width=len(bits_list), bits=bits_to_int(bits_list))

    def rotate_left(self, r: int) -> 'OffBit':
        """Perform cyclic left rotation by r positions."""
        r = r % self.width
        left = ((self.bits << r) & ((1 << self.width) - 1))
        right = (self.bits >> (self.width - r))
        return OffBit(self.width, left | right)

    def parity_blocks(self, block_size: int) -> List[int]:
        """Return parity (count of ones mod 2) per block."""
        blocks = []
        for i in range(0, self.width, block_size):
            mask = ((1 << block_size) - 1) << max(0, self.width - i - block_size)
            chunk = (self.bits & mask) >> max(0, self.width - i - block_size)
            blocks.append(bin(chunk).count("1") % 2)
        return blocks

    def block_counts(self, block_size: int) -> List[int]:
        """Return counts of ones per block."""
        counts = []
        for i in range(0, self.width, block_size):
            mask = ((1 << block_size) - 1) << max(0, self.width - i - block_size)
            chunk = (self.bits & mask) >> max(0, self.width - i - block_size)
            counts.append(bin(chunk).count("1"))
        return counts

    def __repr__(self):
        return f"OffBit(width={self.width}, bits=0b{self.bits:0{self.width}b})"


@dataclass
class Signature:
    """
    Signature: What an observer sees.

    Contains deterministic features extracted from OffBit:
    - block_counts: Number of 1s per block
    - rotated_hash: Rotated hash value (24-bit)
    - parity_vector: Parity bits per block
    """
    block_counts: Tuple[int, ...]
    rotated_hash: int  # 24-bit integer
    parity_vector: Tuple[int, ...]

    def as_tuple(self):
        """Return signature as tuple for hashing/comparison."""
        return (self.block_counts, self.rotated_hash, self.parity_vector)


def observe_offbit(ob: OffBit, block_size: int = 6, rotate_by: int = 5) -> Signature:
    """
    Observe an OffBit and generate its signature.

    Args:
        ob: OffBit to observe
        block_size: Size of blocks for parity/count analysis
        rotate_by: Rotation amount for hash generation

    Returns:
        Signature representing observable features
    """
    bc = tuple(ob.block_counts(block_size))

    hash_width = 24

    # Extract the lowest 24 bits from ob.bits
    extracted_bits = ob.bits & ((1 << hash_width) - 1)

    # Perform cyclic left rotation on these 24 bits
    r = rotate_by % hash_width
    rhash = ((extracted_bits << r) | (extracted_bits >> (hash_width - r))) & ((1 << hash_width) - 1)

    # Parity vector based on full rotated OffBit
    r_obj = ob.rotate_left(rotate_by)
    pv = tuple(r_obj.parity_blocks(block_size))

    return Signature(block_counts=bc, rotated_hash=rhash, parity_vector=pv)


@dataclass
class CoherenceState:
    """
    CoherenceState: Exact rational representation of information state.

    Attributes:
        value: Exact rational value
        log_nrci_error: Log error estimate (Decimal)
        provenance: History of transformations
    """
    value: Fraction
    log_nrci_error: Decimal
    provenance: str

    def refine_backward_by_Y(self, steps: int = 1) -> 'CoherenceState':
        """Apply Y inverse transformation (information → reality)."""
        val_dec = Decimal(self.value.numerator) / Decimal(self.value.denominator)
        val_new_dec = val_dec * (Y_INV_D ** Decimal(steps))
        val_frac = Fraction(int(val_new_dec * (10 ** 12)), 10 ** 12)
        new_log = self.log_nrci_error - Decimal(0.5) * Decimal(steps)
        return CoherenceState(value=val_frac, log_nrci_error=new_log,
                            provenance=f"{self.provenance}|Y^{{-{steps}}}")

    def degrade(self, delta: Decimal) -> 'CoherenceState':
        """Degrade coherence by specified delta."""
        return CoherenceState(self.value, self.log_nrci_error + delta,
                            self.provenance + "|degraded")


def reconstruct_from_signature(sig: Signature, known_rotate_by: int) -> CoherenceState:
    """
    Reconstruct information from signature via inverse rotation.

    Args:
        sig: Signature to reconstruct from
        known_rotate_by: Rotation amount used during observation

    Returns:
        CoherenceState with reconstructed value
    """
    hash_width = 24
    r = known_rotate_by % hash_width

    # Cyclic right rotation (inverse of left rotation)
    unrotated_hash = ((sig.rotated_hash >> r) | (sig.rotated_hash << (hash_width - r))) & ((1 << hash_width) - 1)

    mass = Fraction(unrotated_hash, 1)
    log_err = Decimal('-3.0')  # Conservative error estimate

    return CoherenceState(value=mass, log_nrci_error=log_err,
                         provenance="24bit_rotated_direct_recovery")


def closure_distance(original: OffBit, reconstructed_mass: CoherenceState) -> int:
    """
    Closure distance metric: measures reconstruction fidelity.

    Compares the original OffBit's 24-bit value with the reconstructed
    mass value (also 24-bit). Lower values indicate better closure.

    Args:
        original: Original OffBit
        reconstructed_mass: Reconstructed CoherenceState

    Returns:
        Absolute difference (0 = perfect closure)
    """
    folded_orig = original.bits & ((1 << 24) - 1)
    return abs(folded_orig - (reconstructed_mass.value.numerator & ((1 << 24) - 1)))


def observable_to_seed(freq: float) -> int:
    """
    Convert observable frequency to 24-bit seed.

    Uses logarithmic scaling to map frequencies to seed space.

    Args:
        freq: Frequency in Hz

    Returns:
        24-bit integer seed
    """
    return int(abs(math.log10(freq + 1e-50)) * 1e6) % (1 << 24)


def seed_to_observable(seed: int) -> OffBit:
    """
    Convert seed to OffBit representation.

    Args:
        seed: 24-bit integer seed

    Returns:
        OffBit with 24-bit width
    """
    return OffBit.from_int(width=24, value=seed)


# ===================================================================
# SECTION 4: VERIFICATION TEST
# ===================================================================

def test_forward_ubp_mapping():
    """
    Test Forward UBP Mapping: Seed → Observable → Recovered Seed

    This test validates 100% closure/perfect reconstruction across
    a spectrum of test frequencies.
    """
    print("\n" + "="*70)
    print("UBP CORE VERIFICATION TEST")
    print("="*70)
    print("\nTest: Forward UBP Mapping (Seed → Observable → Recovered Seed)")
    print("-" * 70)

    # Test spectrum: 10 frequencies from 1 Hz to H-alpha line (456 THz)
    test_frequencies = [
        1.0,                # 1 Hz - Extremely low frequency
        60.0,               # 60 Hz - Power line frequency
        440.0,              # 440 Hz - Musical note A4
        1e6,                # 1 MHz - Radio frequency
        1e9,                # 1 GHz - Microwave
        5e14,               # 500 THz - Visible light (orange)
        4.5677e14,          # 456.77 THz - H-alpha line
        1e12,               # 1 THz - Far infrared
        1e8,                # 100 MHz - FM radio
        2.4e9,              # 2.4 GHz - WiFi
    ]

    perfect_closures = 0
    total_tests = len(test_frequencies)

    print(f"\n{'Frequency (Hz)':<20} {'Seed':<12} {'Recovered':<12} {'Closure':<10} {'Status'}")
    print("-" * 70)

    for freq in test_frequencies:
        # Step 1: Convert frequency to seed
        seed = observable_to_seed(freq)

        # Step 2: Create OffBit from seed
        original = seed_to_observable(seed)

        # Step 3: Observe OffBit to get signature
        signature = observe_offbit(original, block_size=6, rotate_by=5)

        # Step 4: Reconstruct from signature
        reconstructed = reconstruct_from_signature(signature, known_rotate_by=5)

        # Step 5: Extract recovered seed
        recovered_seed = int(reconstructed.value) & ((1 << 24) - 1)

        # Step 6: Compute closure distance
        closure = closure_distance(original, reconstructed)

        # Determine status
        if closure == 0 and seed == recovered_seed:
            status = "✓ PERFECT"
            perfect_closures += 1
        else:
            status = "✗ FAILED"

        # Format frequency for display
        if freq >= 1e12:
            freq_str = f"{freq/1e12:.2f} THz"
        elif freq >= 1e9:
            freq_str = f"{freq/1e9:.2f} GHz"
        elif freq >= 1e6:
            freq_str = f"{freq/1e6:.2f} MHz"
        elif freq >= 1e3:
            freq_str = f"{freq/1e3:.2f} kHz"
        else:
            freq_str = f"{freq:.2f} Hz"

        print(f"{freq_str:<20} {seed:<12} {recovered_seed:<12} {closure:<10} {status}")

    print("-" * 70)
    print(f"\nResults: {perfect_closures}/{total_tests} perfect closures")
    print("=" * 70)

    if perfect_closures == total_tests:
        print("\n✓ SUCCESS: 100% closure confirmed - Perfect reconstruction!")
        print("All necessary classes (OffBit, Signature, GolayCodeword, etc.) are available.")
        return True
    else:
        print("\n✗ FAILURE: Not all tests achieved perfect closure")
        return False


# ===================================================================
# MAIN ENTRY POINT
# ===================================================================

if __name__ == "__main__":
    # Run verification test
    success = test_forward_ubp_mapping()

    # Exit with appropriate code
    exit(0 if success else 1)
